
strictness: medium
test-warnings: true
doc-warnings: true
member-warnings: true
inherits:
  - default
ignore-paths:
  - docs/
autodetect: false
max-line-length: 120

pycodestyle:
    run: true

pydocstyle:
  disable:
    - D200
    - D203
    - D205
    - D212
    - D213
    - D404
    - D406
    - D407
    - D408
    - D409
    - D410
    - D411
    - D413
    - D415
    - D416
    - D417

mccabe:
  disable:
    - MC0001  # exception should be removed

pyflakes:
  run: true

pylint:
  disable:
    - import-error
    - too-many-branches
    - too-many-arguments
    - too-many-locals
    - too-many-statements
    - consider-using-f-string
    - missing-module-docstring
    - c-extension-no-member
    - too-many-nested-blocks
    - no-name-in-module

mypy:
  run: true
  options :
    ignore-missing-imports : true
    follow-imports : skip

