site_name: CommonRoad Scenario Designer
theme:
  name: material
  logo: assets/commonroad_white150.png
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - search

nav:
  - Introduction: index.md
  - GUI: gui.md
  - Conversions:
    - Lanelet2: lanelet2.md
    - OpenDRIVE: open_drive.md
    - OSM: osm.md
    - SUMO: sumo.md
