# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sumo_setting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from crdesigner.ui.gui.mwindow.service_layer.gui_resources.size_policies import create_size_policy_for_settings_elements


class Ui_SUMOSettings():

    def __init__(self, h, c, wm, wf, f):
        self.columns = c
        self.height = h
        self.widthm = int(wm * f)
        self.widthf = int(wf * f)
        self.factor = int(f)
    
    def setupUi(self, tabWidget):
        self.scrollArea = QtWidgets.QScrollArea(tabWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaLayout = QtWidgets.QGridLayout(self.scrollArea)

        # single content widget for adding to the scrollArea
        # otherwise scrolling is disabled
        self.contentWrapper = QtWidgets.QWidget()
        self.contentWrapper.setObjectName("ContentWrapper")
        self.HBoxLayout = QtWidgets.QHBoxLayout(self.contentWrapper)
        self.HBoxLayout.setObjectName("gridLayout")
        self.HBoxLayout.setAlignment(QtCore.Qt.AlignLeft)
        self.HBoxLayout.setAlignment(QtCore.Qt.AlignTop)

        # creating columns
        self.content = []
        self.formLayout = []
        for i in range(self.columns):
            self.content.append(QtWidgets.QWidget(self.contentWrapper))
            self.content[i].setObjectName("scrollAreaWidgetContents_" + str(i))
            self.formLayout.append(QtWidgets.QFormLayout(self.content[i]))
            self.formLayout[i].setObjectName("form_" + str(i))
            self.content[i].setMinimumSize(860 * self.factor, 820)
            self.content[i].setLayout(self.formLayout[i])

        column = 0


        #Parameter for the Sumo Settings

        self.label_Parameters = QtWidgets.QLabel(self.content[column])
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Parameters.setFont(font)
        self.label_Parameters.setObjectName("label_10")
        self.formLayout[column].addRow(self.label_Parameters)

        #delta_steps
        # horizontal layout for three widgets (always same structure)
        self.hL_0 = QtWidgets.QHBoxLayout()
        self.hL_0.setObjectName("hL_0")
        self.label_delta_steps = QtWidgets.QLabel(self.content[column])
        self.label_delta_steps.setObjectName("label_delta_steps")
        self.label_delta_steps.setMinimumSize(self.widthf, self.height)
        self.sb_delta_steps = QtWidgets.QSpinBox(self.content[column])
        self.sb_delta_steps.setSuffix("")
        self.sb_delta_steps.setPrefix("")
        self.sb_delta_steps.setMaximum(199)
        self.sb_delta_steps.setProperty("value", 2)
        self.sb_delta_steps.setObjectName("spinBox_delta_steps")
        self.sb_delta_steps.setMinimumSize(self.widthm, self.height)
        self.hL_0.addWidget(self.label_delta_steps)
        self.hL_0.addWidget(self.sb_delta_steps)
        # third widget to seperate columns
        self.hL_0.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_0)

        #lateral_resolution
        self.hL_1 = QtWidgets.QHBoxLayout()
        self.hL_1.setObjectName("hL_1")
        self.sb_lateral_resolution = QtWidgets.QSpinBox(self.content[column])
        self.sb_lateral_resolution.setObjectName("spinBox_2")
        self.sb_lateral_resolution.setMinimumSize(self.widthm, self.height)
        self.label_lateral_resolution = QtWidgets.QLabel(self.content[column])
        self.label_lateral_resolution.setObjectName("label_lateral_resolution")
        self.label_lateral_resolution.setMinimumSize(self.widthf, self.height)
        self.hL_1.addWidget(self.label_lateral_resolution)
        self.hL_1.addWidget(self.sb_lateral_resolution)
        self.hL_1.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_1)

        #compute_orientation
        self.hL_2 = QtWidgets.QHBoxLayout()
        self.hL_2.setObjectName("hL_2")
        self.label_compute_orientation = QtWidgets.QLabel(self.content[column])
        self.label_compute_orientation.setObjectName("label_compute_orientation")
        self.label_compute_orientation.setMinimumSize(self.widthf, self.height)
        self.chk_compute_orientation = QtWidgets.QCheckBox(self.content[column])
        self.chk_compute_orientation.setText("")
        self.chk_compute_orientation.setObjectName("chk_compute_orientation")
        self.chk_compute_orientation.setMinimumSize(self.widthm, self.height)
        self.hL_2.addWidget(self.label_compute_orientation)
        self.hL_2.addWidget(self.chk_compute_orientation)
        self.hL_2.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_2)

        #overwrite_speed_limit
        self.hL_3 = QtWidgets.QHBoxLayout()
        self.hL_3.setObjectName("hL_3")
        self.sb_overwrite_speed_limit = QtWidgets.QSpinBox(self.content[column])
        #self.sb_overwrite_speed_limit.setMinimumSize(QtCore.QSize(200, 0))
        self.sb_overwrite_speed_limit.setMaximum(99999)
        self.sb_overwrite_speed_limit.setProperty("value", 130)
        self.sb_overwrite_speed_limit.setObjectName("spinBox_overwrite_speed_limit")
        self.sb_overwrite_speed_limit.setMinimumSize(self.widthm, self.height)
        self.label_overwrite_speed_limit = QtWidgets.QLabel(self.content[column])
        self.label_overwrite_speed_limit.setObjectName("label_overwrite_speed_limit")
        self.label_overwrite_speed_limit.setMinimumSize(self.widthf, self.height)
        self.label_m_s_1 = QtWidgets.QLabel(self.content[column])
        self.label_m_s_1.setObjectName("label_11")
        self.hL_3.addWidget(self.label_overwrite_speed_limit)
        self.hL_3.addWidget(self.sb_overwrite_speed_limit)
        self.hL_3.addWidget(self.label_m_s_1)
        self.formLayout[column].addRow(self.hL_3)
        
        #unrestricted_max_speed_default
        self.hL_4 = QtWidgets.QHBoxLayout()
        self.hL_4.setObjectName("hL_4")
        self.label_unrestricted_max_speed_default = QtWidgets.QLabel(self.content[column])
        self.label_unrestricted_max_speed_default.setObjectName("label_unrestricted_max_speed_default")
        self.label_unrestricted_max_speed_default.setMinimumSize(self.widthf, self.height)
        self.sb_unrestricted_max_speed_default = QtWidgets.QSpinBox(self.content[column])
        self.sb_unrestricted_max_speed_default.setMinimumSize(QtCore.QSize(200, 0))
        self.sb_unrestricted_max_speed_default.setMaximum(99999)
        self.sb_unrestricted_max_speed_default.setProperty("value", 120)
        self.sb_unrestricted_max_speed_default.setObjectName("spinBox_unrestricted_max_speed_default")
        self.sb_unrestricted_max_speed_default.setMinimumSize(self.widthm, self.height)
        self.label_m_s_2 = QtWidgets.QLabel(self.content[column])
        self.label_m_s_2.setObjectName("label_14")
        self.hL_4.addWidget(self.label_unrestricted_max_speed_default)
        self.hL_4.addWidget(self.sb_unrestricted_max_speed_default)
        self.hL_4.addWidget(self.label_m_s_2)
        self.formLayout[column].addRow(self.hL_4)
        
        #unrestricted_speed_limit_default
        self.hL_5 = QtWidgets.QHBoxLayout()
        self.hL_5.setObjectName("hL_5")
        self.label_unrestricted_speed_limit_default = QtWidgets.QLabel(self.content[column])
        self.label_unrestricted_speed_limit_default.setObjectName("label_13")
        self.label_unrestricted_speed_limit_default.setMinimumSize(self.widthf, self.height)
        self.sb_unrestricted_speed_limit_default = QtWidgets.QSpinBox(self.content[column])
        self.sb_unrestricted_speed_limit_default.setMinimumSize(QtCore.QSize(200, 0))
        self.sb_unrestricted_speed_limit_default.setMaximum(99999)
        self.sb_unrestricted_speed_limit_default.setProperty("value", 130)
        self.sb_unrestricted_speed_limit_default.setObjectName("spinBox_unrestricted_speed_limit_default")
        self.sb_unrestricted_speed_limit_default.setMinimumSize(self.widthm, self.height)
        self.label_m_s_3 = QtWidgets.QLabel(self.content[column])
        self.label_m_s_3.setObjectName("m_s_3")
        self.hL_5.addWidget(self.label_unrestricted_speed_limit_default)
        self.hL_5.addWidget(self.sb_unrestricted_speed_limit_default)
        self.hL_5.addWidget(self.label_m_s_3)
        self.formLayout[column].addRow(self.hL_5)

        #wait_pos_internal_junctions
        self.hL_6 = QtWidgets.QHBoxLayout()
        self.hL_6.setObjectName("hL_6")
        self.label_wait_pos_internal_junctions = QtWidgets.QLabel(self.content[column])
        self.label_wait_pos_internal_junctions.setObjectName("label_16")
        self.label_wait_pos_internal_junctions.setMinimumSize(self.widthf, self.height)
        self.sb_wait_pos_internal_junctions = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_wait_pos_internal_junctions.setMinimumSize(QtCore.QSize(250, 0))
        self.sb_wait_pos_internal_junctions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_wait_pos_internal_junctions.setMinimum(-10000.0)
        self.sb_wait_pos_internal_junctions.setMaximum(1000.0)
        self.sb_wait_pos_internal_junctions.setProperty("value", -4.0)
        self.sb_wait_pos_internal_junctions.setObjectName("sb_wait_pos_internal_junctions")
        self.sb_wait_pos_internal_junctions.setMinimumSize(self.widthm, self.height)
        self.label_m = QtWidgets.QLabel(self.content[column])
        self.label_m.setObjectName("label_12")
        self.hL_6.addWidget(self.label_wait_pos_internal_junctions)
        self.hL_6.addWidget(self.sb_wait_pos_internal_junctions)
        self.hL_6.addWidget(self.label_m)
        self.formLayout[column].addRow(self.hL_6)



        #Parameters for ego vehicle
        self.formLayout[column].addRow(QtWidgets.QLabel(self.content[column]))
        self.label_param_ego_vehicle = QtWidgets.QLabel(self.content[column])
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_param_ego_vehicle.setFont(font)
        self.label_param_ego_vehicle.setObjectName("label_5")
        self.formLayout[column].addRow(self.label_param_ego_vehicle)

        #ego_veh_width
        self.hL_7 = QtWidgets.QHBoxLayout()
        self.hL_7.setObjectName("hL_7")
        self.label_ego_veh_width = QtWidgets.QLabel(self.content[column])
        self.label_ego_veh_width.setObjectName("label_6")
        self.label_ego_veh_width.setMinimumSize(self.widthf, self.height)
        self.sb_ego_veh_width = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_ego_veh_width.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_ego_veh_width.setProperty("value", 2.0)
        self.sb_ego_veh_width.setObjectName("doubleSpinBox_ego_veh_width")
        self.sb_ego_veh_width.setMinimumSize(self.widthm, self.height)
        self.hL_7.addWidget(self.label_ego_veh_width)
        self.hL_7.addWidget(self.sb_ego_veh_width)
        self.hL_7.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_7)

        #ego_veh_length
        self.hL_8 = QtWidgets.QHBoxLayout()
        self.hL_8.setObjectName("hL_8")
        self.label_ego_veh_length = QtWidgets.QLabel(self.content[column])
        self.label_ego_veh_length.setObjectName("label_3")
        self.label_ego_veh_length.setMinimumSize(self.widthf, self.height)
        self.sb_ego_veh_length = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_ego_veh_length.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_ego_veh_length.setProperty("value", 5.0)
        self.sb_ego_veh_length.setObjectName("doubleSpinBox_ego_veh_length")
        self.sb_ego_veh_length.setMinimumSize(self.widthm, self.height)
        self.hL_8.addWidget(self.label_ego_veh_length)
        self.hL_8.addWidget(self.sb_ego_veh_length)
        self.hL_8.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_8)

        #n_ego_vehicles
        self.hL_9 = QtWidgets.QHBoxLayout()
        self.hL_9.setObjectName("hL_9")
        self.label_n_ego_vehicles = QtWidgets.QLabel(self.content[column])
        self.label_n_ego_vehicles.setObjectName("label_4")
        self.label_n_ego_vehicles.setMinimumSize(self.widthf, self.height)
        self.sb_n_ego_vehicles = QtWidgets.QSpinBox(self.content[column])
        self.sb_n_ego_vehicles.setMinimum(0)
        self.sb_n_ego_vehicles.setMaximum(999)
        self.sb_n_ego_vehicles.setProperty("value", 0)
        self.sb_n_ego_vehicles.setObjectName("sb_num_ego_vehicles")
        self.sb_n_ego_vehicles.setMinimumSize(self.widthm, self.height)
        self.hL_9.addWidget(self.label_n_ego_vehicles)
        self.hL_9.addWidget(self.sb_n_ego_vehicles)
        self.hL_9.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_9)

        #ego_ids
        self.hL_10 = QtWidgets.QHBoxLayout()
        self.hL_10.setObjectName("hL_10")
        self.le_ego_ids = QtWidgets.QLineEdit(self.content[column])
        self.le_ego_ids.setText("")
        self.le_ego_ids.setObjectName("le_ego_ids")
        self.le_ego_ids.setMinimumSize(self.widthm, self.height)
        self.le_ego_ids.setSizePolicy(create_size_policy_for_settings_elements())
        self.label_ego_ids = QtWidgets.QLabel(self.content[column])
        self.label_ego_ids.setObjectName("label_20")
        self.label_ego_ids.setMinimumSize(self.widthf, self.height)
        self.hL_10.addWidget(self.label_ego_ids)
        self.hL_10.addWidget(self.le_ego_ids)
        self.hL_10.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_10)

        #ego_start_time
        self.hL_11 = QtWidgets.QHBoxLayout()
        self.hL_11.setObjectName("hL_11")
        self.sb_ego_start_time = QtWidgets.QSpinBox(self.content[column])
        self.sb_ego_start_time.setMaximum(9999)
        self.sb_ego_start_time.setProperty("value", 10)
        self.sb_ego_start_time.setObjectName("spinBox_ego_start_time")
        self.sb_ego_start_time.setMinimumSize(self.widthm, self.height)
        self.label_ego_start_time = QtWidgets.QLabel(self.content[column])
        self.label_ego_start_time.setObjectName("label_7")
        self.label_ego_start_time.setMinimumSize(self.widthf, self.height)
        self.hL_11.addWidget(self.label_ego_start_time)
        self.hL_11.addWidget(self.sb_ego_start_time)
        self.hL_11.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_11)
        
        #departure_time_ego
        self.hL_12 = QtWidgets.QHBoxLayout()
        self.hL_12.setObjectName("hL_12")
        self.label_departure_time_ego = QtWidgets.QLabel(self.content[column])
        self.label_departure_time_ego.setObjectName("label_2")
        self.label_departure_time_ego.setMinimumSize(self.widthf, self.height)
        self.sb_departure_time_ego = QtWidgets.QSpinBox(self.content[column])
        self.sb_departure_time_ego.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_departure_time_ego.setMaximum(99999)
        self.sb_departure_time_ego.setProperty("value", 3)
        self.sb_departure_time_ego.setObjectName("sb")
        self.sb_departure_time_ego.setMinimumSize(self.widthm, self.height)
        self.hL_12.addWidget(self.label_departure_time_ego)
        self.hL_12.addWidget(self.sb_departure_time_ego)
        self.hL_12.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_12)


        #Ego vehicle sync parameters
        self.formLayout[column].addRow(QtWidgets.QLabel(self.content[column]))
        self.label_Ego_vehicle_sync_param = QtWidgets.QLabel(self.content[column])
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Ego_vehicle_sync_param.setFont(font)
        self.label_Ego_vehicle_sync_param.setObjectName("label_17")
        self.formLayout[column].addRow(self.label_Ego_vehicle_sync_param)
        
        #lanelet_check_time_window
        self.hL_13 = QtWidgets.QHBoxLayout()
        self.hL_13.setObjectName("hL_13")
        self.label_lanelet_check_time_window = QtWidgets.QLabel(self.content[column])
        self.label_lanelet_check_time_window.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_lanelet_check_time_window.setObjectName("label_18")
        self.label_lanelet_check_time_window.setMinimumSize(self.widthf, self.height)
        self.sb_lanelet_check_time_window = QtWidgets.QSpinBox(self.content[column])
        self.sb_lanelet_check_time_window.setMinimumSize(QtCore.QSize(200, 0))
        self.sb_lanelet_check_time_window.setMaximum(99999)
        self.sb_lanelet_check_time_window.setProperty("value", 2)
        self.sb_lanelet_check_time_window.setObjectName("spinBox_lanelet_check_time_window")
        self.sb_lanelet_check_time_window.setMinimumSize(self.widthm, self.height)
        self.label_dt = QtWidgets.QLabel(self.content[column])
        self.label_dt.setObjectName("label_8")
        self.hL_13.addWidget(self.label_lanelet_check_time_window)
        self.hL_13.addWidget(self.sb_lanelet_check_time_window)
        self.hL_13.addWidget(self.label_dt)
        self.formLayout[column].addRow(self.hL_13)
        
        #protection_margin
        self.hL_14 = QtWidgets.QHBoxLayout()
        self.hL_14.setObjectName("hL_14")
        self.label_protection_margin = QtWidgets.QLabel(self.content[column])
        self.label_protection_margin.setObjectName("label_19")
        self.label_protection_margin.setMinimumSize(self.widthf, self.height)
        self.sb_protection_margin = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_protection_margin.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_protection_margin.setMaximum(9999999.0)
        self.sb_protection_margin.setProperty("value", 2.0)
        self.sb_protection_margin.setObjectName("doubleSpinBox_protection_margin")
        self.sb_protection_margin.setMinimumSize(self.widthm, self.height)
        self.hL_14.addWidget(self.label_protection_margin)
        self.hL_14.addWidget(self.sb_protection_margin)
        self.hL_14.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_14)
        
        #consistency_window
        self.hL_15 = QtWidgets.QHBoxLayout()
        self.hL_15.setObjectName("hL_15")
        self.label_consistency_window = QtWidgets.QLabel(self.content[column])
        self.label_consistency_window.setObjectName("label_21")
        self.label_consistency_window.setMinimumSize(self.widthf, self.height)
        self.sb_consistency_window = QtWidgets.QSpinBox(self.content[column])
        self.sb_consistency_window.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_consistency_window.setMaximum(99999999)
        self.sb_consistency_window.setProperty("value", 4)
        self.sb_consistency_window.setObjectName("spinBox_consistency_window")
        self.sb_consistency_window.setMinimumSize(self.widthm, self.height)
        self.hL_15.addWidget(self.label_consistency_window)
        self.hL_15.addWidget(self.sb_consistency_window)
        self.hL_15.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_15)

        #lane_change_sync
        self.hL_16 = QtWidgets.QHBoxLayout()
        self.hL_16.setObjectName("hL_16")
        self.label_lane_change_sync = QtWidgets.QLabel(self.content[column])
        self.label_lane_change_sync.setObjectName("label_22")
        self.label_lane_change_sync.setMinimumSize(self.widthf, self.height)
        self.chk_lane_change_sync = QtWidgets.QCheckBox(self.content[column])
        self.chk_lane_change_sync.setText("")
        self.chk_lane_change_sync.setObjectName("chk_lane_change_sync")
        self.chk_lane_change_sync.setMinimumSize(self.widthm, self.height)
        self.hL_16.addWidget(self.label_lane_change_sync)
        self.hL_16.addWidget(self.chk_lane_change_sync)
        self.hL_16.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_16)

        #lane_change_tol
        self.hL_17 = QtWidgets.QHBoxLayout()
        self.hL_17.setObjectName("hL_17")
        self.sb_lane_change_tol = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_lane_change_tol.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_lane_change_tol.setMaximum(99999999.0)
        self.sb_lane_change_tol.setObjectName("doubleSpinBox_lane_change_tol")
        self.sb_lane_change_tol.setMinimumSize(self.widthm, self.height)
        self.label_lane_change_tol = QtWidgets.QLabel(self.content[column])
        self.label_lane_change_tol.setObjectName("label_23")
        self.label_lane_change_tol.setMinimumSize(self.widthf, self.height)
        self.hL_17.addWidget(self.label_lane_change_tol)
        self.hL_17.addWidget(self.sb_lane_change_tol)
        self.hL_17.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_17)

        column = 1
        #Parameter for traffic generation
        self.label_param_traffic_generation = QtWidgets.QLabel(self.content[column])
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_param_traffic_generation.setFont(font)
        self.label_param_traffic_generation.setObjectName("label_27")
        self.formLayout[column].addRow(self.label_param_traffic_generation)
        
        #fringe_factor
        self.hL_18 = QtWidgets.QHBoxLayout()
        self.hL_18.setObjectName("hL_18")
        self.label_fringe_factor = QtWidgets.QLabel(self.content[column])
        self.label_fringe_factor.setObjectName("label_28")
        self.label_fringe_factor.setMinimumSize(self.widthf, self.height)
        self.sb_fringe_factor = QtWidgets.QSpinBox(self.content[column])
        self.sb_fringe_factor.setMaximum(1000000009)
        self.sb_fringe_factor.setProperty("value", 1000000000)
        self.sb_fringe_factor.setObjectName("spinBox_fringe_factor")
        self.sb_fringe_factor.setMinimumSize(self.widthm, self.height)
        self.hL_18.addWidget(self.label_fringe_factor)
        self.hL_18.addWidget(self.sb_fringe_factor)
        self.hL_18.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_18)
        
        #veh_per_second
        self.hL_19 = QtWidgets.QHBoxLayout()
        self.hL_19.setObjectName("hL_19")
        self.label_veh_per_second = QtWidgets.QLabel(self.content[column])
        self.label_veh_per_second.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_veh_per_second.setObjectName("label_29")
        self.label_veh_per_second.setMinimumSize(self.widthf, self.height)
        self.sb_veh_per_second = QtWidgets.QSpinBox(self.content[column])
        self.sb_veh_per_second.setMaximum(9999999)
        self.sb_veh_per_second.setProperty("value", 50)
        self.sb_veh_per_second.setObjectName("spinBox_veh_per_second")
        self.sb_veh_per_second.setMinimumSize(self.widthm, self.height)
        self.hL_19.addWidget(self.label_veh_per_second)
        self.hL_19.addWidget(self.sb_veh_per_second)
        self.hL_19.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_19)
        
        
        #departure_interval_vehicles
        self.hL_20 = QtWidgets.QHBoxLayout()
        self.hL_20.setObjectName("hL_20")
        self.le_departure_interval_vehicles = QtWidgets.QLineEdit(self.content[column])
        self.le_departure_interval_vehicles.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.le_departure_interval_vehicles.setObjectName("le_departure_interval_vehicles")
        self.le_departure_interval_vehicles.setMinimumSize(self.widthm, self.height)
        self.le_departure_interval_vehicles.setSizePolicy(create_size_policy_for_settings_elements())
        self.label_departure_interval_vehicles = QtWidgets.QLabel(self.content[column])
        self.label_departure_interval_vehicles.setObjectName("label_30")
        self.label_departure_interval_vehicles.setMinimumSize(self.widthf, self.height)
        self.hL_20.addWidget(self.label_departure_interval_vehicles)
        self.hL_20.addWidget(self.le_departure_interval_vehicles)
        self.hL_20.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_20)
        
        #n_vehicles_max
        self.hL_21 = QtWidgets.QHBoxLayout()
        self.hL_21.setObjectName("hL_21")
        self.label_n_vehicles_max = QtWidgets.QLabel(self.content[column])
        self.label_n_vehicles_max.setObjectName("label_43")
        self.label_n_vehicles_max.setMinimumSize(self.widthf, self.height)
        self.sb_n_vehicles_max = QtWidgets.QSpinBox(self.content[column])
        self.sb_n_vehicles_max.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_n_vehicles_max.setMaximum(999999999)
        self.sb_n_vehicles_max.setProperty("value", 30)
        self.sb_n_vehicles_max.setObjectName("spinBox_n_vehicles_max")
        self.sb_n_vehicles_max.setMinimumSize(self.widthm, self.height)
        self.hL_21.addWidget(self.label_n_vehicles_max)
        self.hL_21.addWidget(self.sb_n_vehicles_max)
        self.hL_21.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_21)

        #max_veh_per_km
        self.hL_22 = QtWidgets.QHBoxLayout()
        self.hL_22.setObjectName("hL_22")
        self.label_max_veh_per_km = QtWidgets.QLabel(self.content[column])
        self.label_max_veh_per_km.setObjectName("label_9")
        self.label_max_veh_per_km.setMinimumSize(self.widthf, self.height)
        self.sb_max_veh_per_km = QtWidgets.QSpinBox(self.content[column])
        self.sb_max_veh_per_km.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_max_veh_per_km.setMaximum(9999999)
        self.sb_max_veh_per_km.setProperty("value", 70)
        self.sb_max_veh_per_km.setObjectName("spinBox_max_veh_per_km")
        self.sb_max_veh_per_km.setMinimumSize(self.widthm, self.height)
        self.hL_22.addWidget(self.label_max_veh_per_km)
        self.hL_22.addWidget(self.sb_max_veh_per_km)
        self.hL_22.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_22)
        
        #random_seed
        self.hL_23 = QtWidgets.QHBoxLayout()
        self.hL_23.setObjectName("hL_23")
        self.sb_random_seed = QtWidgets.QSpinBox(self.content[column])
        self.sb_random_seed.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_random_seed.setMaximum(99999999)
        self.sb_random_seed.setProperty("value", 1234)
        self.sb_random_seed.setObjectName("spinBox_random_seed")
        self.sb_random_seed.setMinimumSize(self.widthm, self.height)
        self.label_random_seed = QtWidgets.QLabel(self.content[column])
        self.label_random_seed.setObjectName("label_15")
        self.label_random_seed.setMinimumSize(self.widthf, self.height)
        self.hL_23.addWidget(self.label_random_seed)
        self.hL_23.addWidget(self.sb_random_seed)
        self.hL_23.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_23)
        
        #other vehicle size bound
        self.formLayout[column].addRow(QtWidgets.QLabel(self.content[column]))
        self.label_size_bound = QtWidgets.QLabel(self.content[column])
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_size_bound.setFont(font)
        self.label_size_bound.setObjectName("label_31")
        self.formLayout[column].addRow(self.label_size_bound)
        
        #vehicle_length_interval
        self.hL_24 = QtWidgets.QHBoxLayout()
        self.hL_24.setObjectName("hL_24")
        self.sb_vehicle_length_interval = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_vehicle_length_interval.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_vehicle_length_interval.setMaximum(99999999.0)
        self.sb_vehicle_length_interval.setProperty("value", 0.4)
        self.sb_vehicle_length_interval.setObjectName("doubleSpinBox_vehicle_length_interval")
        self.sb_vehicle_length_interval.setMinimumSize(self.widthm, self.height)
        self.label_vehicle_length_interval = QtWidgets.QLabel(self.content[column])
        self.label_vehicle_length_interval.setObjectName("label_32")
        self.label_vehicle_length_interval.setMinimumSize(self.widthf, self.height)
        self.hL_24.addWidget(self.label_vehicle_length_interval)
        self.hL_24.addWidget(self.sb_vehicle_length_interval)
        self.hL_24.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_24)

        #vehicle_width_interval
        self.hL_25 = QtWidgets.QHBoxLayout()
        self.hL_25.setObjectName("hL_25")
        self.sb_vehicle_width_interval = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_vehicle_width_interval.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_vehicle_width_interval.setMaximum(9999999.0)
        self.sb_vehicle_width_interval.setProperty("value", 0.2)
        self.sb_vehicle_width_interval.setObjectName("doubleSpinBox_vehicle_width_interval")
        self.sb_vehicle_width_interval.setMinimumSize(self.widthm, self.height)
        self.label_vehicle_width_interval = QtWidgets.QLabel(self.content[column])
        self.label_vehicle_width_interval.setObjectName("label_41")
        self.label_vehicle_width_interval.setMinimumSize(self.widthf, self.height)
        self.hL_25.addWidget(self.label_vehicle_width_interval)
        self.hL_25.addWidget(self.sb_vehicle_width_interval)
        self.hL_25.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_25)
        
        #Parameter of vehicle classes
        self.formLayout[column].addRow(QtWidgets.QLabel(self.content[column]))
        self.label_param_vehicle_classes = QtWidgets.QLabel(self.content[column])
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_param_vehicle_classes.setFont(font)
        self.label_param_vehicle_classes.setObjectName("label_24")
        self.formLayout[column].addRow(self.label_param_vehicle_classes)
        
        
        #Passenger
        self.hL_26 = QtWidgets.QHBoxLayout()
        self.hL_26.setObjectName("hL_26")
        self.label_Passenger = QtWidgets.QLabel(self.content[column])
        self.label_Passenger.setObjectName("label_25")
        self.label_Passenger.setMinimumSize(self.widthf, self.height)
        self.sb_passenger = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_passenger.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_passenger.setProperty("value", 4.0)
        self.sb_passenger.setObjectName("doubleSpinBox_passenger")
        self.sb_passenger.setMinimumSize(self.widthm, self.height)
        self.hL_26.addWidget(self.label_Passenger)
        self.hL_26.addWidget(self.sb_passenger)
        self.hL_26.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_26)

        #Truck
        self.hL_27 = QtWidgets.QHBoxLayout()
        self.hL_27.setObjectName("hL_27")
        self.label_Truck = QtWidgets.QLabel(self.content[column])
        self.label_Truck.setObjectName("label_26")
        self.label_Truck.setMinimumSize(self.widthf, self.height)
        self.sb_truck = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_truck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_truck.setProperty("value", 0.8)
        self.sb_truck.setObjectName("doubleSpinBox_truck")
        self.sb_truck.setMinimumSize(self.widthm, self.height)
        self.hL_27.addWidget(self.label_Truck)
        self.hL_27.addWidget(self.sb_truck)
        self.hL_27.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_27)
        
        #Bus
        self.hL_28 = QtWidgets.QHBoxLayout()
        self.hL_28.setObjectName("hL_28")
        self.label_Bus = QtWidgets.QLabel(self.content[column])
        self.label_Bus.setObjectName("label_33")
        self.label_Bus.setMinimumSize(self.widthf, self.height)
        self.sb_bus = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_bus.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_bus.setProperty("value", 0.3)
        self.sb_bus.setObjectName("doubleSpinBox_bus")
        self.sb_bus.setMinimumSize(self.widthm, self.height)
        self.hL_28.addWidget(self.label_Bus)
        self.hL_28.addWidget(self.sb_bus)
        self.hL_28.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_28)

        #Bicycle
        self.hL_29 = QtWidgets.QHBoxLayout()
        self.hL_29.setObjectName("hL_29")
        self.label_Bicycle = QtWidgets.QLabel(self.content[column])
        self.label_Bicycle.setObjectName("label_35")
        self.label_Bicycle.setMinimumSize(self.widthf, self.height)
        self.sb_bicycle = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_bicycle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_bicycle.setProperty("value", 0.2)
        self.sb_bicycle.setObjectName("doubleSpinBox_bicycle")
        self.sb_bicycle.setMinimumSize(self.widthm, self.height)
        self.hL_29.addWidget(self.label_Bicycle)
        self.hL_29.addWidget(self.sb_bicycle)
        self.hL_29.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_29)
        
        #Pedestrian
        self.hL_30 = QtWidgets.QHBoxLayout()
        self.hL_30.setObjectName("hL_30")
        self.label_Pedestrian = QtWidgets.QLabel(self.content[column])
        self.label_Pedestrian.setObjectName("label_34")
        self.label_Pedestrian.setMinimumSize(self.widthf, self.height)
        self.sb_pedestrian = QtWidgets.QDoubleSpinBox(self.content[column])
        self.sb_pedestrian.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_pedestrian.setObjectName("doubleSpinBox_pedestrian")
        self.sb_pedestrian.setMinimumSize(self.widthm, self.height)
        self.hL_30.addWidget(self.label_Pedestrian)
        self.hL_30.addWidget(self.sb_pedestrian)
        self.hL_30.addWidget(QtWidgets.QLabel(self.content[column]))
        self.formLayout[column].addRow(self.hL_30)


        for i in range(self.columns):
            self.HBoxLayout.addWidget(self.content[i])

        self.scrollArea.setWidget(self.contentWrapper)

        #self.retranslateUi(tabWidget)
        QtCore.QMetaObject.connectSlotsByName(tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_compute_orientation.setText(_translate("MainWindow", "compute_orientation"))
        self.label_unrestricted_max_speed_default.setToolTip(_translate("MainWindow", "[m/s] default max. speed for SUMO for unrestricted sped limits"))
        self.label_unrestricted_max_speed_default.setText(_translate("MainWindow", "unrestricted_max_speed_def"))
        self.label_lateral_resolution.setText(_translate("MainWindow", "lateral_resolution"))
        self.label_delta_steps.setToolTip(_translate("MainWindow", "number of sub-steps simulated in SUMO during every dt"))
        self.label_delta_steps.setText(_translate("MainWindow", "delta_steps"))
        self.label_overwrite_speed_limit.setText(_translate("MainWindow", "overwrite_speed_limit"))
        self.label_max_veh_per_km.setToolTip(_translate("MainWindow", "max. number of vehicles per km"))
        self.label_max_veh_per_km.setText(_translate("MainWindow", "max_veh_per_km"))
        self.label_departure_time_ego.setText(_translate("MainWindow", "departure_time_ego"))
        self.label_Parameters.setText(_translate("MainWindow", "Parameters for the SUMO settings"))
        self.label_n_ego_vehicles.setToolTip(_translate("MainWindow", "number of ego vehicles"))
        self.label_n_ego_vehicles.setText(_translate("MainWindow", "n_ego_vehicles"))
        self.label_protection_margin.setToolTip(_translate("MainWindow", "The absolute margin allowed between the planner position and ego position in SUMO"))
        self.label_protection_margin.setText(_translate("MainWindow", "protection_margin"))
        self.label_ego_veh_length.setText(_translate("MainWindow", "ego_veh_length"))
        self.label_n_vehicles_max.setToolTip(_translate("MainWindow", "max. number of vehicles in route file"))
        self.label_n_vehicles_max.setText(_translate("MainWindow", "n_vehicles_max"))
        self.label_Passenger.setText(_translate("MainWindow", "Passenger"))
        self.label_Pedestrian.setText(_translate("MainWindow", "Pedestrian"))
        self.label_veh_per_second.setToolTip(_translate("MainWindow", "number of vehicle departures per second"))
        self.label_veh_per_second.setText(_translate("MainWindow", "veh_per_second"))
        self.label_vehicle_length_interval.setText(_translate("MainWindow", "vehicle_length_interval"))
        self.label_unrestricted_speed_limit_default.setToolTip(_translate("MainWindow", "[m/s] default speed limit when no speed_limit is given"))
        self.label_unrestricted_speed_limit_default.setText(_translate("MainWindow", "unrestricted_speed_limit_def"))
        self.label_fringe_factor.setText(_translate("MainWindow", "fringe_factor"))
        self.label_param_traffic_generation.setText(_translate("MainWindow", "Parameters for traffic generation"))
        self.label_lanelet_check_time_window.setToolTip(_translate("MainWindow", "Time window to detect the lanelet change in seconds"))
        self.label_lanelet_check_time_window.setText(_translate("MainWindow", "lanelet_check_time_window"))
        self.label_Bus.setText(_translate("MainWindow", "Bus"))
        self.label_param_vehicle_classes.setToolTip(_translate("MainWindow", "probability distribution of different vehicle classes. Do not need to sum up to 1."))
        self.label_param_vehicle_classes.setText(_translate("MainWindow", "Parameter of vehicle classes"))
        self.label_lane_change_sync.setToolTip(_translate("MainWindow", "Used to limit the sync mechanism only to move xy"))
        self.label_lane_change_sync.setText(_translate("MainWindow", "lane_change_sync"))
        self.label_wait_pos_internal_junctions.setToolTip(_translate("MainWindow", "[m] shifted waiting position at junction (equivalent to SUMO\'s contPos parameter)"))
        self.label_wait_pos_internal_junctions.setText(_translate("MainWindow", "wait_pos_internal_junctions"))
        self.label_consistency_window.setToolTip(_translate("MainWindow", "Variable can be used  to force the consistency to certain number of steps"))
        self.label_consistency_window.setText(_translate("MainWindow", "consistency_window"))
        self.label_lane_change_tol.setToolTip(_translate("MainWindow", "tolerance for detecting start of lane change"))
        self.label_lane_change_tol.setText(_translate("MainWindow", "lane_change_tol"))
        self.label_ego_start_time.setText(_translate("MainWindow", "ego_start_time"))
        self.label_dt.setText(_translate("MainWindow", " / dt"))
        self.label_m_s_1.setText(_translate("MainWindow", " / 3.6  [m/s] "))
        self.label_departure_interval_vehicles.setToolTip(_translate("MainWindow", "Interval of departure times for vehicles"))
        self.label_departure_interval_vehicles.setText(_translate("MainWindow", "departure_interval_vehicles"))
        self.label_Truck.setText(_translate("MainWindow", "Truck"))
        self.label_vehicle_width_interval.setText(_translate("MainWindow", "vehicle_width_interval"))
        self.label_size_bound.setText(_translate("MainWindow", "other vehicles size bound:"))
        self.label_param_ego_vehicle.setText(_translate("MainWindow", "Parameters for ego vehicle"))
        self.label_m_s_2.setText(_translate("MainWindow", " / 3.6  [m/s] "))
        self.label_m_s_3.setText(_translate("MainWindow", " / 3.6  [m/s] "))
        self.label_Ego_vehicle_sync_param.setText(_translate("MainWindow", "Ego vehicle sync parameters"))
        self.label_ego_ids.setToolTip(_translate("MainWindow", "if desired ids of ego_vehicle known, specify here"))
        self.label_ego_ids.setText(_translate("MainWindow", "ego_ids"))
        self.label_random_seed.setText(_translate("MainWindow", "random_seed"))
        self.label_ego_veh_width.setText(_translate("MainWindow", "ego_veh_width"))
        self.label_m.setText(_translate("MainWindow", " [m] "))
        self.label_Bicycle.setText(_translate("MainWindow", "Bicycle"))
        self.le_departure_interval_vehicles.setText(_translate("MainWindow", "(0, 30)"))
        self.le_ego_ids.setToolTip(_translate("MainWindow", "List[int] = []"))

