# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.l_region = QtWidgets.QLabel(self.frame)
        self.l_region.setObjectName("l_region")
        self.gridLayout_2.addWidget(self.l_region, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.range_input = QtWidgets.QSpinBox(self.frame)
        self.range_input.setMaximum(10000)
        self.range_input.setProperty("value", 100)
        self.range_input.setObjectName("range_input")
        self.gridLayout_2.addWidget(self.range_input, 1, 2, 1, 1)
        self.coordinate_input = QtWidgets.QLineEdit(self.frame)
        self.coordinate_input.setMinimumSize(QtCore.QSize(120, 0))
        self.coordinate_input.setObjectName("coordinate_input")
        self.gridLayout_2.addWidget(self.coordinate_input, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 5, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_selected_file = QtWidgets.QLabel(self.frame_2)
        self.l_selected_file.setObjectName("l_selected_file")
        self.gridLayout_3.addWidget(self.l_selected_file, 0, 1, 1, 1)
        self.b_load_file = QtWidgets.QPushButton(self.frame_2)
        self.b_load_file.setMaximumSize(QtCore.QSize(75, 16777215))
        self.b_load_file.setObjectName("b_load_file")
        self.gridLayout_3.addWidget(self.b_load_file, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 2, 0, 1, 1)
        self.rb_download_map = QtWidgets.QRadioButton(self.frame_3)
        self.rb_download_map.setObjectName("rb_download_map")
        self.gridLayout_4.addWidget(self.rb_download_map, 3, 0, 1, 1)
        self.chk_user_edit = QtWidgets.QCheckBox(self.frame_3)
        self.chk_user_edit.setChecked(True)
        self.chk_user_edit.setObjectName("chk_user_edit")
        self.gridLayout_4.addWidget(self.chk_user_edit, 8, 0, 1, 1)
        self.rb_load_file = QtWidgets.QRadioButton(self.frame_3)
        self.rb_load_file.setEnabled(True)
        self.rb_load_file.setChecked(True)
        self.rb_load_file.setObjectName("rb_load_file")
        self.gridLayout_4.addWidget(self.rb_load_file, 1, 0, 1, 1)
        self.input_picked_output = QtWidgets.QLabel(self.frame_3)
        self.input_picked_output.setObjectName("input_picked_output")
        self.gridLayout_4.addWidget(self.input_picked_output, 7, 0, 1, 1)
        self.b_start = QtWidgets.QPushButton(self.frame_3)
        self.b_start.setObjectName("b_start")
        self.gridLayout_4.addWidget(self.b_start, 9, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.input_bench_id = QtWidgets.QLineEdit(self.frame_4)
        self.input_bench_id.setObjectName("input_bench_id")
        self.gridLayout_5.addWidget(self.input_bench_id, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 8, 0, 1, 1)
        self.b_load_state = QtWidgets.QPushButton(self.centralwidget)
        self.b_load_state.setObjectName("b_load_state")
        self.gridLayout.addWidget(self.b_load_state, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 1)
        self.b_download = QtWidgets.QPushButton(self.centralwidget)
        self.b_download.setObjectName("b_download")
        self.gridLayout.addWidget(self.b_download, 6, 0, 1, 1)
        self.b_settings = QtWidgets.QPushButton(self.centralwidget)
        self.b_settings.setToolTip("")
        self.b_settings.setObjectName("b_settings")
        self.gridLayout.addWidget(self.b_settings, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "osm2cr"))
        self.label_5.setText(_translate("MainWindow", "Range"))
        self.l_region.setText(_translate("MainWindow", "Coordinates Valid"))
        self.label_3.setText(_translate("MainWindow", "Coordinates (Lat-Long):"))
        self.coordinate_input.setText(_translate("MainWindow", "48.262545, 11.668124"))
        self.l_selected_file.setText(_translate("MainWindow", "No File"))
        self.b_load_file.setText(_translate("MainWindow", "Select File"))
        self.rb_download_map.setText(_translate("MainWindow", "Download OSM Map:"))
        self.chk_user_edit.setText(_translate("MainWindow", "Edit Scenario manually"))
        self.rb_load_file.setText(_translate("MainWindow", "Load OSM File"))
        self.input_picked_output.setText(_translate("MainWindow", "No file picked"))
        self.b_start.setToolTip(_translate("MainWindow", "Start conversion with selected input"))
        self.b_start.setText(_translate("MainWindow", "Start Conversion"))
        self.input_bench_id.setText(_translate("MainWindow", "test_bench"))
        self.label.setText(_translate("MainWindow", "BenchmarkID"))
        self.b_load_state.setToolTip(_translate("MainWindow", "Continue editing a scenario"))
        self.b_load_state.setText(_translate("MainWindow", "Load Edit State"))
        self.b_download.setToolTip(_translate("MainWindow", "Download the selected Region as OSM map"))
        self.b_download.setText(_translate("MainWindow", "Download OSM"))
        self.b_settings.setText(_translate("MainWindow", "Edit Settings"))

