# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingUi(object):
    def setupUi(self, SettingUi):
        SettingUi.setObjectName("SettingUi")
        SettingUi.resize(887, 777)
        self.gridLayout = QtWidgets.QGridLayout(SettingUi)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingUi)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_od2cr = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_od2cr.sizePolicy().hasHeightForWidth())
        self.tab_od2cr.setSizePolicy(sizePolicy)
        self.tab_od2cr.setObjectName("tab_od2cr")
        self.tabWidget.addTab(self.tab_od2cr, "")
        self.tab_osm2cr = QtWidgets.QWidget()
        self.tab_osm2cr.setObjectName("tab_osm2cr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_osm2cr)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_osm2cr)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 829, 1267))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_86.setObjectName("label_86")
        self.gridLayout_5.addWidget(self.label_86, 41, 0, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_87.setObjectName("label_87")
        self.gridLayout_5.addWidget(self.label_87, 9, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_88.setObjectName("label_88")
        self.gridLayout_5.addWidget(self.label_88, 31, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_89.setObjectName("label_89")
        self.gridLayout_5.addWidget(self.label_89, 35, 0, 1, 1)
        self.le_tags_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_tags_3.setObjectName("le_tags_3")
        self.gridLayout_5.addWidget(self.le_tags_3, 5, 2, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_90.setObjectName("label_90")
        self.gridLayout_5.addWidget(self.label_90, 33, 0, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_91.setObjectName("label_91")
        self.gridLayout_5.addWidget(self.label_91, 20, 0, 1, 1)
        self.chk_make_contiguous_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_make_contiguous_3.setText("")
        self.chk_make_contiguous_3.setObjectName("chk_make_contiguous_3")
        self.gridLayout_5.addWidget(self.chk_make_contiguous_3, 18, 2, 1, 1)
        self.chk_utm_coordinates_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_utm_coordinates_3.setText("")
        self.chk_utm_coordinates_3.setObjectName("chk_utm_coordinates_3")
        self.gridLayout_5.addWidget(self.chk_utm_coordinates_3, 28, 2, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_92.setObjectName("label_92")
        self.gridLayout_5.addWidget(self.label_92, 8, 0, 1, 1)
        self.sb_intersection_distance_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_intersection_distance_3.setMaximum(1000.0)
        self.sb_intersection_distance_3.setObjectName("sb_intersection_distance_3")
        self.gridLayout_5.addWidget(self.sb_intersection_distance_3, 35, 2, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.gridLayout_5.addWidget(self.label_93, 0, 0, 1, 1)
        self.le_source_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_source_3.setObjectName("le_source_3")
        self.gridLayout_5.addWidget(self.le_source_3, 4, 2, 1, 1)
        self.chb_aerial_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chb_aerial_3.setText("")
        self.chb_aerial_3.setObjectName("chb_aerial_3")
        self.gridLayout_5.addWidget(self.chb_aerial_3, 8, 2, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.gridLayout_5.addWidget(self.label_94, 7, 0, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_95.setObjectName("label_95")
        self.gridLayout_5.addWidget(self.label_95, 13, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.gridLayout_5.addWidget(self.label_96, 30, 0, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_97.setObjectName("label_97")
        self.gridLayout_5.addWidget(self.label_97, 39, 0, 1, 1)
        self.sb_zoom_level_3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_zoom_level_3.setMinimum(1)
        self.sb_zoom_level_3.setMaximum(23)
        self.sb_zoom_level_3.setObjectName("sb_zoom_level_3")
        self.gridLayout_5.addWidget(self.sb_zoom_level_3, 10, 2, 1, 1)
        self.sb_eart_radius_3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_eart_radius_3.setMaximum(100000000)
        self.sb_eart_radius_3.setProperty("value", 6371000)
        self.sb_eart_radius_3.setObjectName("sb_eart_radius_3")
        self.gridLayout_5.addWidget(self.sb_eart_radius_3, 31, 2, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_98.setObjectName("label_98")
        self.gridLayout_5.addWidget(self.label_98, 1, 0, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_99.setObjectName("label_99")
        self.gridLayout_5.addWidget(self.label_99, 10, 0, 1, 1)
        self.chk_load_tunnels_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_load_tunnels_3.setText("")
        self.chk_load_tunnels_3.setObjectName("chk_load_tunnels_3")
        self.gridLayout_5.addWidget(self.chk_load_tunnels_3, 17, 2, 1, 1)
        self.chk_split_corners_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_split_corners_3.setText("")
        self.chk_split_corners_3.setObjectName("chk_split_corners_3")
        self.gridLayout_5.addWidget(self.chk_split_corners_3, 19, 2, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_100.setObjectName("label_100")
        self.gridLayout_5.addWidget(self.label_100, 17, 0, 1, 1)
        self.le_img_save_path_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_img_save_path_3.setObjectName("le_img_save_path_3")
        self.gridLayout_5.addWidget(self.le_img_save_path_3, 9, 2, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_5.addWidget(self.label_101, 16, 0, 1, 1)
        self.sb_soft_angle_treshold_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_soft_angle_treshold_3.setMaximum(180.0)
        self.sb_soft_angle_treshold_3.setObjectName("sb_soft_angle_treshold_3")
        self.gridLayout_5.addWidget(self.sb_soft_angle_treshold_3, 37, 2, 1, 1)
        self.sb_bezier_parameter_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_bezier_parameter_3.setMaximum(0.5)
        self.sb_bezier_parameter_3.setProperty("value", 0.35)
        self.sb_bezier_parameter_3.setObjectName("sb_bezier_parameter_3")
        self.gridLayout_5.addWidget(self.sb_bezier_parameter_3, 34, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_102.setObjectName("label_102")
        self.gridLayout_5.addWidget(self.label_102, 38, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_103.setObjectName("label_103")
        self.gridLayout_5.addWidget(self.label_103, 3, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_104.setObjectName("label_104")
        self.gridLayout_5.addWidget(self.label_104, 12, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_105.setObjectName("label_105")
        self.gridLayout_5.addWidget(self.label_105, 15, 0, 1, 1)
        self.le_benchmark_id_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_benchmark_id_3.setObjectName("le_benchmark_id_3")
        self.gridLayout_5.addWidget(self.le_benchmark_id_3, 1, 2, 1, 1)
        self.sb_time_step_size_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_time_step_size_3.setMaximum(1000.0)
        self.sb_time_step_size_3.setObjectName("sb_time_step_size_3")
        self.gridLayout_5.addWidget(self.sb_time_step_size_3, 6, 2, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_106.setObjectName("label_106")
        self.gridLayout_5.addWidget(self.label_106, 6, 0, 1, 1)
        self.le_affiliation_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_affiliation_3.setObjectName("le_affiliation_3")
        self.gridLayout_5.addWidget(self.le_affiliation_3, 3, 2, 1, 1)
        self.le_coordinates_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_coordinates_3.setObjectName("le_coordinates_3")
        self.gridLayout_5.addWidget(self.le_coordinates_3, 14, 2, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_107.setObjectName("label_107")
        self.gridLayout_5.addWidget(self.label_107, 5, 0, 1, 1)
        self.sb_internal_interpolation_distance_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_internal_interpolation_distance_3.setMinimum(0.01)
        self.sb_internal_interpolation_distance_3.setMaximum(1000.0)
        self.sb_internal_interpolation_distance_3.setObjectName("sb_internal_interpolation_distance_3")
        self.gridLayout_5.addWidget(self.sb_internal_interpolation_distance_3, 33, 2, 1, 1)
        self.btn_edit_lane_counts_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_edit_lane_counts_3.setObjectName("btn_edit_lane_counts_3")
        self.gridLayout_5.addWidget(self.btn_edit_lane_counts_3, 22, 2, 1, 1)
        self.btn_edit_speed_limits_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_edit_speed_limits_3.setObjectName("btn_edit_speed_limits_3")
        self.gridLayout_5.addWidget(self.btn_edit_speed_limits_3, 24, 2, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_108.setObjectName("label_108")
        self.gridLayout_5.addWidget(self.label_108, 22, 0, 1, 1)
        self.chk_delete_short_edges_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_delete_short_edges_3.setText("")
        self.chk_delete_short_edges_3.setObjectName("chk_delete_short_edges_3")
        self.gridLayout_5.addWidget(self.chk_delete_short_edges_3, 32, 2, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_109.setFont(font)
        self.label_109.setObjectName("label_109")
        self.gridLayout_5.addWidget(self.label_109, 25, 0, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_110.setObjectName("label_110")
        self.gridLayout_5.addWidget(self.label_110, 19, 0, 1, 1)
        self.sb_compression_threshold_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_compression_threshold_3.setMaximum(1000.0)
        self.sb_compression_threshold_3.setObjectName("sb_compression_threshold_3")
        self.gridLayout_5.addWidget(self.sb_compression_threshold_3, 27, 2, 1, 1)
        self.btn_edit_street_types_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_edit_street_types_3.setObjectName("btn_edit_street_types_3")
        self.gridLayout_5.addWidget(self.btn_edit_street_types_3, 21, 2, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_111.setObjectName("label_111")
        self.gridLayout_5.addWidget(self.label_111, 27, 0, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_112.setObjectName("label_112")
        self.gridLayout_5.addWidget(self.label_112, 26, 0, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_113.setObjectName("label_113")
        self.gridLayout_5.addWidget(self.label_113, 28, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_114.setObjectName("label_114")
        self.gridLayout_5.addWidget(self.label_114, 32, 0, 1, 1)
        self.le_bing_maps_key_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_bing_maps_key_3.setObjectName("le_bing_maps_key_3")
        self.gridLayout_5.addWidget(self.le_bing_maps_key_3, 11, 2, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_115.setObjectName("label_115")
        self.gridLayout_5.addWidget(self.label_115, 21, 0, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_116.setObjectName("label_116")
        self.gridLayout_5.addWidget(self.label_116, 11, 0, 1, 1)
        self.sb_interpolation_distance_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_interpolation_distance_3.setMinimum(0.01)
        self.sb_interpolation_distance_3.setMaximum(1000.0)
        self.sb_interpolation_distance_3.setObjectName("sb_interpolation_distance_3")
        self.gridLayout_5.addWidget(self.sb_interpolation_distance_3, 26, 2, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_117.setObjectName("label_117")
        self.gridLayout_5.addWidget(self.label_117, 24, 0, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_118.setObjectName("label_118")
        self.gridLayout_5.addWidget(self.label_118, 23, 0, 1, 1)
        self.chk_use_restrictions_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_use_restrictions_3.setText("")
        self.chk_use_restrictions_3.setObjectName("chk_use_restrictions_3")
        self.gridLayout_5.addWidget(self.chk_use_restrictions_3, 20, 2, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_119.setObjectName("label_119")
        self.gridLayout_5.addWidget(self.label_119, 40, 0, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_120.setObjectName("label_120")
        self.gridLayout_5.addWidget(self.label_120, 34, 0, 1, 1)
        self.sb_merge_distance_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_merge_distance_3.setMaximum(1000000.0)
        self.sb_merge_distance_3.setObjectName("sb_merge_distance_3")
        self.gridLayout_5.addWidget(self.sb_merge_distance_3, 41, 2, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_121.setObjectName("label_121")
        self.gridLayout_5.addWidget(self.label_121, 18, 0, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_122.setObjectName("label_122")
        self.gridLayout_5.addWidget(self.label_122, 37, 0, 1, 1)
        self.btn_edit_lane_widths_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_edit_lane_widths_3.setObjectName("btn_edit_lane_widths_3")
        self.gridLayout_5.addWidget(self.btn_edit_lane_widths_3, 23, 2, 1, 1)
        self.sb_cluster_length_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_cluster_length_3.setMaximum(1000000.0)
        self.sb_cluster_length_3.setObjectName("sb_cluster_length_3")
        self.gridLayout_5.addWidget(self.sb_cluster_length_3, 39, 2, 1, 1)
        self.sb_lane_segment_angle_treshold_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_lane_segment_angle_treshold_3.setMaximum(180.0)
        self.sb_lane_segment_angle_treshold_3.setObjectName("sb_lane_segment_angle_treshold_3")
        self.gridLayout_5.addWidget(self.sb_lane_segment_angle_treshold_3, 38, 2, 1, 1)
        self.sb_cluster_length_treshold_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_cluster_length_treshold_3.setMaximum(1000000.0)
        self.sb_cluster_length_treshold_3.setObjectName("sb_cluster_length_treshold_3")
        self.gridLayout_5.addWidget(self.sb_cluster_length_treshold_3, 40, 2, 1, 1)
        self.sb_donwload_radius_3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.sb_donwload_radius_3.setMaximum(1000000)
        self.sb_donwload_radius_3.setProperty("value", 200)
        self.sb_donwload_radius_3.setObjectName("sb_donwload_radius_3")
        self.gridLayout_5.addWidget(self.sb_donwload_radius_3, 15, 2, 1, 1)
        self.chk_filter_points_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_filter_points_3.setText("")
        self.chk_filter_points_3.setObjectName("chk_filter_points_3")
        self.gridLayout_5.addWidget(self.chk_filter_points_3, 29, 2, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_123.setObjectName("label_123")
        self.gridLayout_5.addWidget(self.label_123, 2, 0, 1, 1)
        self.chk_intersection_distance_respect_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.chk_intersection_distance_respect_3.setText("")
        self.chk_intersection_distance_respect_3.setObjectName("chk_intersection_distance_respect_3")
        self.gridLayout_5.addWidget(self.chk_intersection_distance_respect_3, 36, 2, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_124.setObjectName("label_124")
        self.gridLayout_5.addWidget(self.label_124, 4, 0, 1, 1)
        self.label_125 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_125.setObjectName("label_125")
        self.gridLayout_5.addWidget(self.label_125, 14, 0, 1, 1)
        self.le_author_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_author_3.setObjectName("le_author_3")
        self.gridLayout_5.addWidget(self.le_author_3, 2, 2, 1, 1)
        self.label_126 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_126.setObjectName("label_126")
        self.gridLayout_5.addWidget(self.label_126, 29, 0, 1, 1)
        self.le_save_path_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_save_path_3.setObjectName("le_save_path_3")
        self.gridLayout_5.addWidget(self.le_save_path_3, 13, 2, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_127.setObjectName("label_127")
        self.gridLayout_5.addWidget(self.label_127, 36, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame = QtWidgets.QFrame(self.tab_osm2cr)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_close_2 = QtWidgets.QPushButton(self.frame)
        self.btn_close_2.setObjectName("btn_close_2")
        self.gridLayout_6.addWidget(self.btn_close_2, 0, 2, 1, 1)
        self.btn_save_2 = QtWidgets.QPushButton(self.frame)
        self.btn_save_2.setObjectName("btn_save_2")
        self.gridLayout_6.addWidget(self.btn_save_2, 0, 1, 1, 1)
        self.btn_restore_defaults_2 = QtWidgets.QPushButton(self.frame)
        self.btn_restore_defaults_2.setObjectName("btn_restore_defaults_2")
        self.gridLayout_6.addWidget(self.btn_restore_defaults_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_osm2cr, "")
        self.tab_sumo2cr = QtWidgets.QWidget()
        self.tab_sumo2cr.setObjectName("tab_sumo2cr")
        self.tabWidget.addTab(self.tab_sumo2cr, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(SettingUi)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingUi)

    def retranslateUi(self, SettingUi):
        _translate = QtCore.QCoreApplication.translate
        SettingUi.setWindowTitle(_translate("SettingUi", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_od2cr), _translate("SettingUi", "Config setting for OD2CR"))
        self.label_86.setText(_translate("SettingUi", "Merge Distance"))
        self.label_87.setText(_translate("SettingUi", "Image Save Path"))
        self.label_88.setText(_translate("SettingUi", "Earth Radius"))
        self.label_89.setText(_translate("SettingUi", "Intersection Distance"))
        self.label_90.setText(_translate("SettingUi", "Internal Interpolation Distance"))
        self.label_91.setText(_translate("SettingUi", "Use OSM Restrictions"))
        self.label_92.setText(_translate("SettingUi", "Show Aerial Images"))
        self.label_93.setText(_translate("SettingUi", "Benchmark"))
        self.label_94.setText(_translate("SettingUi", "Aerial Images"))
        self.label_95.setText(_translate("SettingUi", "Save Path"))
        self.label_96.setText(_translate("SettingUi", "Internal Settings"))
        self.label_97.setText(_translate("SettingUi", "Cluster Length"))
        self.label_98.setText(_translate("SettingUi", "Benchmark ID"))
        self.label_99.setText(_translate("SettingUi", "Zoom Level"))
        self.label_100.setText(_translate("SettingUi", "Load Tunnels"))
        self.label_101.setText(_translate("SettingUi", "Scenario Settings"))
        self.label_102.setText(_translate("SettingUi", "Lane Segment Angle Threshold"))
        self.label_103.setText(_translate("SettingUi", "Affiliation"))
        self.label_104.setText(_translate("SettingUi", "Map Download"))
        self.label_105.setText(_translate("SettingUi", "Donwload Radius"))
        self.label_106.setText(_translate("SettingUi", "Timestep Size"))
        self.label_107.setText(_translate("SettingUi", "Tags"))
        self.btn_edit_lane_counts_3.setText(_translate("SettingUi", "Show"))
        self.btn_edit_speed_limits_3.setText(_translate("SettingUi", "Show"))
        self.label_108.setText(_translate("SettingUi", "Lane Counts"))
        self.label_109.setText(_translate("SettingUi", "Export Settings"))
        self.label_110.setText(_translate("SettingUi", "Split at Corners"))
        self.btn_edit_street_types_3.setText(_translate("SettingUi", "Show"))
        self.label_111.setText(_translate("SettingUi", "Compression Threshold"))
        self.label_112.setText(_translate("SettingUi", "Interpolation Distance"))
        self.label_113.setText(_translate("SettingUi", "UTM Coordinates"))
        self.label_114.setText(_translate("SettingUi", "Delete Short Edges"))
        self.label_115.setText(_translate("SettingUi", "Converted Street Types"))
        self.label_116.setText(_translate("SettingUi", "Bing Maps Key"))
        self.label_117.setText(_translate("SettingUi", "Speed Limits"))
        self.label_118.setText(_translate("SettingUi", "Lane Widths"))
        self.label_119.setText(_translate("SettingUi", "Cluster Length Treshold"))
        self.label_120.setText(_translate("SettingUi", "Bezier Parameter"))
        self.label_121.setText(_translate("SettingUi", "Make Contiguous"))
        self.label_122.setText(_translate("SettingUi", "Soft Angle Threshold"))
        self.btn_edit_lane_widths_3.setText(_translate("SettingUi", "Show"))
        self.label_123.setText(_translate("SettingUi", "Author"))
        self.label_124.setText(_translate("SettingUi", "Source"))
        self.label_125.setText(_translate("SettingUi", "Coordinates"))
        self.label_126.setText(_translate("SettingUi", "Filter Points"))
        self.label_127.setText(_translate("SettingUi", "Intersection Distance with\n"
"respect to other roads"))
        self.btn_close_2.setText(_translate("SettingUi", "Close Settings"))
        self.btn_save_2.setText(_translate("SettingUi", "Save"))
        self.btn_restore_defaults_2.setText(_translate("SettingUi", "Restore Defaults"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_osm2cr), _translate("SettingUi", "Config setting for OSM2CR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sumo2cr), _translate("SettingUi", "Config setting for SUMO2CR"))

