Accepted_highways_mainlayer:
- motorway
- trunk
- primary
- secondary
- tertiary
- unclassified
- residential
- motorway_link
- trunk_link
- primary_link
- secondary_link
- tertiary_link
- living_street
- service
Accepted_highways_sublayer:
- path
- footway
- cycleway
Accepted_traffic_sign:
- All
Aerial_images: false
Affilation: Technical University of Munich, Germany
Author: Automated converter by Maximilian Rieger
Benchmark_id: ZAM_Test-1_1_T-1
Bezier_parameter: 0.35
Bing_maps_key: null
Cluster_length: 10.0
Compression_threshold: 0.05
Crossing_lanelettype: crosswalk
Delete_invalid_lanes: true
Delete_short_edges: true
Download_coordinates: (48.262447, 11.657881)
Download_edge_length: 200
Earth_radius: 6371000
Excluded_traffic_sign: null
Export_in_utm: false
Extract_sublayer: false
Filter: true
Geonames_username: demo
Image_save_path: files/imagery/
Interpolation_distance: 0.5
Interpolation_distance_internal: 0.5
Intersection_cropping_with_respect_to_roads: true
Intersection_distance: 4.0
Intersection_distance_sublayer: 1.0
Intersection_enhancement: true
Intersection_straight_threshold: 35.0
Lane_segment_angle: 5.0
Lanecounts:
  cycleway: 1
  footway: 1
  living_street: 2
  motorway: 6
  motorway_link: 2
  path: 1
  primary: 2
  primary_link: 2
  residential: 2
  secondary: 2
  secondary_link: 2
  service: 2
  tertiary: 2
  tertiary_link: 2
  trunk: 4
  trunk_link: 2
  unclassified: 2
Lanelettype: urban
Lanewidths:
  cycleway: 2.0
  footway: 2.0
  living_street: 3.5
  motorway: 3.5
  motorway_link: 3.5
  path: 2.0
  primary: 3.5
  primary_link: 3.5
  residential: 3.5
  secondary: 3.5
  secondary_link: 3.5
  service: 3.5
  tertiary: 3.5
  tertiary_link: 3.5
  trunk: 3.5
  trunk_link: 3.5
  unclassified: 3.5
Least_cluster_length: 10.0
Load_tunnels: false
Make_contiguous: false
Mapillary_categories:
- warning
- regulatory
- information
- complementary
Mapillary_client_id: demo
Merge_distance: 3.5
Recognized_turnlanes:
- left
- through
- right
- slight_right
- slight_left
- merge_to_left
- merge_to_right
- through;right
- left;through
- left;through;right
- left;right
- none
Remove_unconnected_lanelets: true
Rrejected_tags:
- area: true
Save_path: files/
Soft_angle_threshold: 55.0
Source: OpenStreetMaps (OSM)
Speed_limits:
  cycleway: 20
  footway: 8
  living_street: 7
  motorway: 120
  motorway_link: 80
  path: 8
  primary: 100
  primary_link: 80
  residential: 50
  secondary: 100
  secondary_link: 80
  service: 10
  tertiary: 100
  tertiary_link: 80
  trunk: 100
  trunk_link: 80
  unclassified: 80
Split_at_corner: true
Sublayer_lanelettype: sidewalk
Tags: urban
Timestepsize: 0.1
Traffic_light_cycle:
- red_phase: 57
- red_yellow_phase: 3
- green_phase: 37
- yellow_phase: 3
Traffic_sign_keys:
- traffic_sign
- overtaking
- traffic_signals:direction
- maxspeed
Traffic_sign_values:
- traffic_signals
- stop
- give_way
- city_limit
Use_restrictions: true
User_edit: false
Zoom_level: 19
