Autofocus: false
Axis_visible: None
Darkmode: false
Draw_incoming_lanelets: false
Draw_intersection_labels: false
Draw_intersections: false
Draw_obstacle_direction: false
Draw_obstacle_icons: false
Draw_obstacle_labels: false
Draw_obstacle_signals: false
Draw_occupancy: false
Draw_successors: false
Draw_traffic_lights: false
Draw_traffic_signs: false
Draw_trajectory: false
Legend: false
