Benchmark_id: DEU_test
Author: Automated converter by Maximilian Rieger
Affiliation: Technical University of Munich, Germany
Source: OpenStreetMaps (OSM)
Tags: urban
Geoname_id: -999
Gps_latitude: 123.45
Gps_longitude: 123.45
Timestepsize: 0.1
Lanelettype: urban
Aerial_images: False
Image_save_path: files/imagery/
Zoom_level: 19
Save_path: files/
Download_edge_length: 200
Download_coordinates: (48.262447, 11.657881)
Load_tunnels: False
Make_contiguous: False
Split_at_corner: True
Use_restrictions: True
Accepted_highways_mainlayer: [
    motorway,
    trunk,
    primary,
    secondary,
    tertiary,
    unclassified,
    residential,
    motorway_link,
    trunk_link,
    primary_link,
    secondary_link,
    tertiary_link,
    living_street,
    service
]
Extract_sublayer: True
Accepted_highways_sublayer: [
    path,
    footway,
    cycleway
]
Sublayer_lanelettype: sidewalk
Crossing_lanelettype: crosswalk
Rejected_tags: {
    area: yes
}
Lanecounts: {
    motorway: 6,
    trunk: 4,
    primary: 2,
    secondary: 2,
    tertiary: 2,
    unclassified: 2,
    residential: 2,
    motorway_link: 2,
    trunk_link: 2,
    primary_link: 2,
    secondary_link: 2,
    tertiary_link: 2,
    living_street: 2,
    service: 2,
    path: 1,
    footway: 1,
    cycleway: 1
}
Lanewidths: {
    motorway: 3.5,
    trunk: 3.5,
    primary: 3.5,
    secondary: 3.5,
    tertiary: 3.5,
    unclassified: 3.5,
    residential: 3.5,
    motorway_link: 3.5,
    trunk_link: 3.5,
    primary_link: 3.5,
    secondary_link: 3.5,
    tertiary_link: 3.5,
    living_street: 3.5,
    service: 3.5,
    path: 2.0,
    footway: 2.0,
    cycleway: 2.0
}
Speed_limits: {
    motorway: 120,
    trunk: 100,
    primary: 100,
    secondary: 100,
    tertiary: 100,
    unclassified: 80,
    residential: 50,
    motorway_link: 80,
    trunk_link: 80,
    primary_link: 80,
    secondary_link: 80,
    tertiary_link: 80,
    living_street: 7,
    service: 10,
    path: 8,
    footway: 8,
    cycleway: 20
}
Interpolation_distance: 0.5
Compression_threshold: 0.05
Export_in_utm: False
Filter: True
Earth_radius: 6371000
Delete_short_edges: False
Interpolation_distance_internal: 0.25
Bezier_parameter: 0.35
Intersection_distance: 20.0
Intersection_distance_sublayer: 1.0
Intersection_cropping_with_respect_to_roads: True
Soft_angle_threshold: 55.0
Lane_segment_angle: 5.0
Cluster_Length: 10.0
Least_cluster_length: 10.0
Merge_distance: 3.5
Intersection_straight_threshold: 35.0
User_edit: False
Recognised_turnlanes: [
    left,
    through,
    right,
    merge_to_left,
    merge_to_right,
    through;right,
    left;through,
    left;through;right,
    left;right,
    none,
]
Traffic_sign_values: [
    traffic_signals,
    stop,
    give_way,
    city_limit,
]
Traffic_sign_keys: [
    traffic_sign,
    overtaking,
    traffic_signals:direction,
    maxspeed,
]