# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edge_edit_embedding.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EdgeEdit(object):
    def setupUi(self, EdgeEdit):
        EdgeEdit.setObjectName("EdgeEdit")
        EdgeEdit.resize(730, 677)
        self.centralwidget = QtWidgets.QWidget(EdgeEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.plot_groupBox.setMinimumSize(QtCore.QSize(1200, 800))
        self.plot_groupBox.setTitle("")
        self.plot_groupBox.setObjectName("plot_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.plot_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_frame = QtWidgets.QVBoxLayout()
        self.plot_frame.setObjectName("plot_frame")
        self.gridLayout_2.addLayout(self.plot_frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.plot_groupBox, 0, 1, 1, 1)
        self.Buttons = QtWidgets.QWidget(self.centralwidget)
        self.Buttons.setMinimumSize(QtCore.QSize(100, 0))
        self.Buttons.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Buttons.setObjectName("Buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Buttons)
        self.verticalLayout.setContentsMargins(0, -1, -1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.Buttons)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.b_save = QtWidgets.QPushButton(self.Buttons)
        self.b_save.setObjectName("b_save")
        self.verticalLayout.addWidget(self.b_save)
        self.b_load = QtWidgets.QPushButton(self.Buttons)
        self.b_load.setObjectName("b_load")
        self.verticalLayout.addWidget(self.b_load)
        self.b_undo = QtWidgets.QPushButton(self.Buttons)
        self.b_undo.setObjectName("b_undo")
        self.verticalLayout.addWidget(self.b_undo)
        self.b_redo = QtWidgets.QPushButton(self.Buttons)
        self.b_redo.setObjectName("b_redo")
        self.verticalLayout.addWidget(self.b_redo)
        self.b_delete = QtWidgets.QPushButton(self.Buttons)
        self.b_delete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.b_delete.setObjectName("b_delete")
        self.verticalLayout.addWidget(self.b_delete)
        self.b_split = QtWidgets.QPushButton(self.Buttons)
        self.b_split.setObjectName("b_split")
        self.verticalLayout.addWidget(self.b_split)
        self.b_new_waypoint = QtWidgets.QPushButton(self.Buttons)
        self.b_new_waypoint.setObjectName("b_new_waypoint")
        self.verticalLayout.addWidget(self.b_new_waypoint)
        self.b_new_edge = QtWidgets.QPushButton(self.Buttons)
        self.b_new_edge.setObjectName("b_new_edge")
        self.verticalLayout.addWidget(self.b_new_edge)
        self.b_set_widths = QtWidgets.QPushButton(self.Buttons)
        self.b_set_widths.setObjectName("b_set_widths")
        self.verticalLayout.addWidget(self.b_set_widths)
        self.chk_move = QtWidgets.QCheckBox(self.Buttons)
        self.chk_move.setObjectName("chk_move")
        self.verticalLayout.addWidget(self.chk_move)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.Buttons, 0, 0, 1, 1)
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.verticalWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.verticalWidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sp_backward_lanes = QtWidgets.QSpinBox(self.widget)
        self.sp_backward_lanes.setObjectName("sp_backward_lanes")
        self.gridLayout_3.addWidget(self.sp_backward_lanes, 3, 1, 1, 1)
        self.sp_forward_lanes = QtWidgets.QSpinBox(self.widget)
        self.sp_forward_lanes.setObjectName("sp_forward_lanes")
        self.gridLayout_3.addWidget(self.sp_forward_lanes, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.co_road_type = QtWidgets.QComboBox(self.widget)
        self.co_road_type.setObjectName("co_road_type")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.gridLayout_3.addWidget(self.co_road_type, 0, 1, 1, 1)
        self.sp_lane_count = QtWidgets.QSpinBox(self.widget)
        self.sp_lane_count.setMinimum(1)
        self.sp_lane_count.setObjectName("sp_lane_count")
        self.gridLayout_3.addWidget(self.sp_lane_count, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.ch_oneway = QtWidgets.QCheckBox(self.widget)
        self.ch_oneway.setText("")
        self.ch_oneway.setObjectName("ch_oneway")
        self.gridLayout_3.addWidget(self.ch_oneway, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.sp_lane_width = QtWidgets.QDoubleSpinBox(self.widget)
        self.sp_lane_width.setDecimals(3)
        self.sp_lane_width.setMaximum(1000.0)
        self.sp_lane_width.setSingleStep(0.1)
        self.sp_lane_width.setProperty("value", 2.0)
        self.sp_lane_width.setObjectName("sp_lane_width")
        self.gridLayout_3.addWidget(self.sp_lane_width, 5, 1, 1, 1)
        self.sp_speed_limit = QtWidgets.QSpinBox(self.widget)
        self.sp_speed_limit.setMinimum(1)
        self.sp_speed_limit.setMaximum(1000)
        self.sp_speed_limit.setSingleStep(10)
        self.sp_speed_limit.setProperty("value", 50)
        self.sp_speed_limit.setObjectName("sp_speed_limit")
        self.gridLayout_3.addWidget(self.sp_speed_limit, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.b_flip = QtWidgets.QPushButton(self.widget)
        self.b_flip.setObjectName("b_flip")
        self.gridLayout_3.addWidget(self.b_flip, 7, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.verticalWidget, 0, 2, 1, 1)
        self.b_finalize = QtWidgets.QPushButton(self.centralwidget)
        self.b_finalize.setObjectName("b_finalize")
        self.gridLayout.addWidget(self.b_finalize, 1, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.verticalWidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0)
        self.traffic_sign_1 = QtWidgets.QPushButton(self.widget_2)
        self.traffic_sign_1.setObjectName("traffic_sign_1")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui_src/button_traffic_light.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traffic_sign_1.setIcon(icon1)
        self.traffic_sign_1.setIconSize(QtCore.QSize(50, 50))
        self.gridLayout_4.addWidget(self.traffic_sign_1, 1, 0)
        self.traffic_sign_2 = QtWidgets.QPushButton(self.widget_2)
        self.traffic_sign_2.setObjectName("traffic_sign_2")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui_src/button_yeld.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traffic_sign_2.setIcon(icon2)
        self.traffic_sign_2.setIconSize(QtCore.QSize(50, 50))
        self.gridLayout_4.addWidget(self.traffic_sign_2, 1, 1)
        self.traffic_sign_3 = QtWidgets.QPushButton(self.widget_2)
        self.traffic_sign_3.setObjectName("traffic_sign_3")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui_src/button_stop.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traffic_sign_3.setIcon(icon3)
        self.traffic_sign_3.setIconSize(QtCore.QSize(50, 50))
        self.gridLayout_4.addWidget(self.traffic_sign_3, 2, 0)
        self.traffic_sign_4 = QtWidgets.QPushButton(self.widget_2)
        self.traffic_sign_4.setObjectName("traffic_sign_4")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui_src/button_roundabout.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.traffic_sign_4.setIcon(icon4)
        self.traffic_sign_4.setIconSize(QtCore.QSize(50, 50))
        self.gridLayout_4.addWidget(self.traffic_sign_4, 2, 1)

        self.gridLayout.addWidget(self.verticalWidget, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        EdgeEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EdgeEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 38))
        self.menubar.setObjectName("menubar")
        EdgeEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EdgeEdit)
        self.statusbar.setObjectName("statusbar")
        EdgeEdit.setStatusBar(self.statusbar)

        self.retranslateUi(EdgeEdit)
        QtCore.QMetaObject.connectSlotsByName(EdgeEdit)

    def retranslateUi(self, EdgeEdit):
        _translate = QtCore.QCoreApplication.translate
        EdgeEdit.setWindowTitle(_translate("EdgeEdit", "Edge Edit"))
        self.label.setText(_translate("EdgeEdit", "Actions"))
        self.b_save.setToolTip(_translate("EdgeEdit", "ctrl+s"))
        self.b_save.setText(_translate("EdgeEdit", "save"))
        self.b_load.setToolTip(_translate("EdgeEdit", "ctrl + l"))
        self.b_load.setText(_translate("EdgeEdit", "load"))
        self.b_undo.setToolTip(_translate("EdgeEdit", "ctrl + z"))
        self.b_undo.setText(_translate("EdgeEdit", "undo"))
        self.b_redo.setToolTip(_translate("EdgeEdit", "ctrl + shift + z"))
        self.b_redo.setText(_translate("EdgeEdit", "redo"))
        self.b_delete.setToolTip(_translate("EdgeEdit", "del"))
        self.b_delete.setText(_translate("EdgeEdit", "delete"))
        self.b_split.setToolTip(_translate("EdgeEdit", "ctrl + d"))
        self.b_split.setText(_translate("EdgeEdit", "split"))
        self.b_new_waypoint.setToolTip(_translate("EdgeEdit", "ctrl + n"))
        self.b_new_waypoint.setText(_translate("EdgeEdit", "new point"))
        self.b_new_edge.setToolTip(_translate("EdgeEdit", "ctrl + e"))
        self.b_new_edge.setText(_translate("EdgeEdit", "new edge"))
        self.b_set_widths.setText(_translate("EdgeEdit", "set widths"))
        self.chk_move.setText(_translate("EdgeEdit", "Move"))
        self.label_6.setText(_translate("EdgeEdit", "Oneway"))
        self.label_4.setText(_translate("EdgeEdit", "Nr of backward"))
        self.co_road_type.setItemText(0, _translate("EdgeEdit", "Motorway"))
        self.co_road_type.setItemText(1, _translate("EdgeEdit", "Motorway Link"))
        self.co_road_type.setItemText(2, _translate("EdgeEdit", "Trunk"))
        self.co_road_type.setItemText(3, _translate("EdgeEdit", "Trunk Link"))
        self.co_road_type.setItemText(4, _translate("EdgeEdit", "Primary"))
        self.co_road_type.setItemText(5, _translate("EdgeEdit", "Primary Link"))
        self.co_road_type.setItemText(6, _translate("EdgeEdit", "Secondary"))
        self.co_road_type.setItemText(7, _translate("EdgeEdit", "Secondary Link"))
        self.co_road_type.setItemText(8, _translate("EdgeEdit", "Tertiary"))
        self.co_road_type.setItemText(9, _translate("EdgeEdit", "Tertiary Link"))
        self.co_road_type.setItemText(10, _translate("EdgeEdit", "Unclassified"))
        self.co_road_type.setItemText(11, _translate("EdgeEdit", "Residential"))
        self.co_road_type.setItemText(12, _translate("EdgeEdit", "Living Street"))
        self.co_road_type.setItemText(13, _translate("EdgeEdit", "Service"))
        self.label_7.setText(_translate("EdgeEdit", "Lane width"))
        self.label_5.setText(_translate("EdgeEdit", "Road Type"))
        self.label_3.setText(_translate("EdgeEdit", "Nr of forward"))
        self.label_8.setText(_translate("EdgeEdit", "Speed Limit"))
        self.label_2.setText(_translate("EdgeEdit", "Nr of Lanes"))
        self.b_flip.setText(_translate("EdgeEdit", "flip direction"))
        self.b_finalize.setText(_translate("EdgeEdit", "Finalize Edit"))
