# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edge_edit_embedding.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EdgeEdit(object):
    def setupUi(self, EdgeEdit):
        EdgeEdit.setObjectName("EdgeEdit")
        EdgeEdit.resize(1137, 756)
        self.centralwidget = QtWidgets.QWidget(EdgeEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.plot_groupBox.setMinimumSize(QtCore.QSize(400, 600))
        self.plot_groupBox.setTitle("")
        self.plot_groupBox.setObjectName("plot_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plot_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_frame = QtWidgets.QVBoxLayout()
        self.plot_frame.setObjectName("plot_frame")
        self.verticalLayout.addLayout(self.plot_frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.plot_groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.plot_groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.plot_groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.b_finalize = QtWidgets.QPushButton(self.plot_groupBox)
        self.b_finalize.setObjectName("b_finalize")
        self.horizontalLayout.addWidget(self.b_finalize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 12)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addWidget(self.plot_groupBox, 0, 1, 1, 1)
        self.Buttons = QtWidgets.QWidget(self.centralwidget)
        self.Buttons.setMinimumSize(QtCore.QSize(235, 0))
        self.Buttons.setMaximumSize(QtCore.QSize(235, 16777215))
        self.Buttons.setObjectName("Buttons")
        self.label = QtWidgets.QLabel(self.Buttons)
        self.label.setGeometry(QtCore.QRect(10, 9, 55, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.chk_move = QtWidgets.QCheckBox(self.Buttons)
        self.chk_move.setGeometry(QtCore.QRect(10, 230, 63, 23))
        self.chk_move.setObjectName("chk_move")
        self.widget = QtWidgets.QWidget(self.Buttons)
        self.widget.setGeometry(QtCore.QRect(0, 270, 231, 293))
        self.widget.setMinimumSize(QtCore.QSize(182, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 7, 0, 1, 1)
        self.sp_backward_lanes = QtWidgets.QSpinBox(self.widget)
        self.sp_backward_lanes.setObjectName("sp_backward_lanes")
        self.gridLayout_3.addWidget(self.sp_backward_lanes, 4, 1, 1, 1)
        self.co_road_type = QtWidgets.QComboBox(self.widget)
        self.co_road_type.setObjectName("co_road_type")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.co_road_type.addItem("")
        self.gridLayout_3.addWidget(self.co_road_type, 1, 1, 1, 1)
        self.sp_forward_lanes = QtWidgets.QSpinBox(self.widget)
        self.sp_forward_lanes.setObjectName("sp_forward_lanes")
        self.gridLayout_3.addWidget(self.sp_forward_lanes, 3, 1, 1, 1)
        self.sp_speed_limit = QtWidgets.QSpinBox(self.widget)
        self.sp_speed_limit.setMinimum(1)
        self.sp_speed_limit.setMaximum(1000)
        self.sp_speed_limit.setSingleStep(10)
        self.sp_speed_limit.setProperty("value", 50)
        self.sp_speed_limit.setObjectName("sp_speed_limit")
        self.gridLayout_3.addWidget(self.sp_speed_limit, 7, 1, 1, 1)
        self.b_flip = QtWidgets.QPushButton(self.widget)
        self.b_flip.setObjectName("b_flip")
        self.gridLayout_3.addWidget(self.b_flip, 8, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1)
        self.ch_oneway = QtWidgets.QCheckBox(self.widget)
        self.ch_oneway.setText("")
        self.ch_oneway.setObjectName("ch_oneway")
        self.gridLayout_3.addWidget(self.ch_oneway, 5, 1, 1, 1)
        self.sp_lane_count = QtWidgets.QSpinBox(self.widget)
        self.sp_lane_count.setMinimum(1)
        self.sp_lane_count.setObjectName("sp_lane_count")
        self.gridLayout_3.addWidget(self.sp_lane_count, 2, 1, 1, 1)
        self.sp_lane_width = QtWidgets.QDoubleSpinBox(self.widget)
        self.sp_lane_width.setDecimals(3)
        self.sp_lane_width.setMaximum(1000.0)
        self.sp_lane_width.setSingleStep(0.1)
        self.sp_lane_width.setProperty("value", 2.0)
        self.sp_lane_width.setObjectName("sp_lane_width")
        self.gridLayout_3.addWidget(self.sp_lane_width, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.widget1 = QtWidgets.QWidget(self.Buttons)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 211, 191))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.b_save = QtWidgets.QPushButton(self.widget1)
        self.b_save.setObjectName("b_save")
        self.gridLayout_4.addWidget(self.b_save, 0, 0, 1, 1)
        self.b_undo = QtWidgets.QPushButton(self.widget1)
        self.b_undo.setObjectName("b_undo")
        self.gridLayout_4.addWidget(self.b_undo, 2, 0, 1, 1)
        self.b_delete = QtWidgets.QPushButton(self.widget1)
        self.b_delete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.b_delete.setObjectName("b_delete")
        self.gridLayout_4.addWidget(self.b_delete, 4, 0, 1, 1)
        self.b_new_edge = QtWidgets.QPushButton(self.widget1)
        self.b_new_edge.setObjectName("b_new_edge")
        self.gridLayout_4.addWidget(self.b_new_edge, 7, 0, 1, 1)
        self.b_load = QtWidgets.QPushButton(self.widget1)
        self.b_load.setObjectName("b_load")
        self.gridLayout_4.addWidget(self.b_load, 0, 1, 1, 1)
        self.b_redo = QtWidgets.QPushButton(self.widget1)
        self.b_redo.setObjectName("b_redo")
        self.gridLayout_4.addWidget(self.b_redo, 2, 1, 1, 1)
        self.b_new_waypoint = QtWidgets.QPushButton(self.widget1)
        self.b_new_waypoint.setObjectName("b_new_waypoint")
        self.gridLayout_4.addWidget(self.b_new_waypoint, 4, 1, 1, 1)
        self.b_split = QtWidgets.QPushButton(self.widget1)
        self.b_split.setObjectName("b_split")
        self.gridLayout_4.addWidget(self.b_split, 5, 0, 1, 1)
        self.b_set_widths = QtWidgets.QPushButton(self.widget1)
        self.b_set_widths.setObjectName("b_set_widths")
        self.gridLayout_4.addWidget(self.b_set_widths, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.Buttons, 0, 0, 2, 1)
        EdgeEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EdgeEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1137, 28))
        self.menubar.setObjectName("menubar")
        EdgeEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EdgeEdit)
        self.statusbar.setObjectName("statusbar")
        EdgeEdit.setStatusBar(self.statusbar)

        self.retranslateUi(EdgeEdit)
        QtCore.QMetaObject.connectSlotsByName(EdgeEdit)

    def retranslateUi(self, EdgeEdit):
        _translate = QtCore.QCoreApplication.translate
        EdgeEdit.setWindowTitle(_translate("EdgeEdit", "Edge Edit"))
        self.pushButton.setText(_translate("EdgeEdit", "Sparsing"))
        self.pushButton_2.setText(_translate("EdgeEdit", "Edge Editing"))
        self.pushButton_3.setText(_translate("EdgeEdit", "Lane Link Editing"))
        self.b_finalize.setText(_translate("EdgeEdit", "Finalize Edit"))
        self.label.setText(_translate("EdgeEdit", "Actions"))
        self.chk_move.setText(_translate("EdgeEdit", "Move"))
        self.label_3.setText(_translate("EdgeEdit", "Nr of forward"))
        self.label_5.setText(_translate("EdgeEdit", "Road Type"))
        self.label_4.setText(_translate("EdgeEdit", "Nr of backward"))
        self.label_8.setText(_translate("EdgeEdit", "Speed Limit"))
        self.co_road_type.setItemText(0, _translate("EdgeEdit", "Motorway"))
        self.co_road_type.setItemText(1, _translate("EdgeEdit", "Motorway Link"))
        self.co_road_type.setItemText(2, _translate("EdgeEdit", "Trunk"))
        self.co_road_type.setItemText(3, _translate("EdgeEdit", "Trunk Link"))
        self.co_road_type.setItemText(4, _translate("EdgeEdit", "Primary"))
        self.co_road_type.setItemText(5, _translate("EdgeEdit", "Primary Link"))
        self.co_road_type.setItemText(6, _translate("EdgeEdit", "Secondary"))
        self.co_road_type.setItemText(7, _translate("EdgeEdit", "Secondary Link"))
        self.co_road_type.setItemText(8, _translate("EdgeEdit", "Tertiary"))
        self.co_road_type.setItemText(9, _translate("EdgeEdit", "Tertiary Link"))
        self.co_road_type.setItemText(10, _translate("EdgeEdit", "Unclassified"))
        self.co_road_type.setItemText(11, _translate("EdgeEdit", "Residential"))
        self.co_road_type.setItemText(12, _translate("EdgeEdit", "Living Street"))
        self.co_road_type.setItemText(13, _translate("EdgeEdit", "Service"))
        self.b_flip.setText(_translate("EdgeEdit", "flip direction"))
        self.label_6.setText(_translate("EdgeEdit", "Oneway"))
        self.label_7.setText(_translate("EdgeEdit", "Lane width"))
        self.label_2.setText(_translate("EdgeEdit", "Nr of Lanes"))
        self.label_9.setText(_translate("EdgeEdit", "Road Information"))
        self.b_save.setToolTip(_translate("EdgeEdit", "ctrl+s"))
        self.b_save.setText(_translate("EdgeEdit", "save"))
        self.b_undo.setToolTip(_translate("EdgeEdit", "ctrl + z"))
        self.b_undo.setText(_translate("EdgeEdit", "undo"))
        self.b_delete.setToolTip(_translate("EdgeEdit", "del"))
        self.b_delete.setText(_translate("EdgeEdit", "delete"))
        self.b_new_edge.setToolTip(_translate("EdgeEdit", "ctrl + e"))
        self.b_new_edge.setText(_translate("EdgeEdit", "new edge"))
        self.b_load.setToolTip(_translate("EdgeEdit", "ctrl + l"))
        self.b_load.setText(_translate("EdgeEdit", "load"))
        self.b_redo.setToolTip(_translate("EdgeEdit", "ctrl + shift + z"))
        self.b_redo.setText(_translate("EdgeEdit", "redo"))
        self.b_new_waypoint.setToolTip(_translate("EdgeEdit", "ctrl + n"))
        self.b_new_waypoint.setText(_translate("EdgeEdit", "new point"))
        self.b_split.setToolTip(_translate("EdgeEdit", "ctrl + d"))
        self.b_split.setText(_translate("EdgeEdit", "split"))
        self.b_set_widths.setText(_translate("EdgeEdit", "set widths"))

