# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lane_link_edit_embedding.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LaneLinkEdit(object):
    def setupUi(self, LaneLinkEdit):
        LaneLinkEdit.setObjectName("LaneLinkEdit")
        LaneLinkEdit.resize(1027, 737)
        self.centralwidget = QtWidgets.QWidget(LaneLinkEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.plot_groupBox.setMinimumSize(QtCore.QSize(400, 400))
        self.plot_groupBox.setTitle("")
        self.plot_groupBox.setObjectName("plot_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.plot_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_frame = QtWidgets.QVBoxLayout()
        self.plot_frame.setObjectName("plot_frame")
        self.gridLayout_2.addLayout(self.plot_frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.plot_groupBox, 0, 1, 1, 1)
        self.Buttons = QtWidgets.QWidget(self.centralwidget)
        self.Buttons.setMinimumSize(QtCore.QSize(70, 0))
        self.Buttons.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Buttons.setObjectName("Buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Buttons)
        self.verticalLayout.setContentsMargins(0, -1, -1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.Buttons)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.b_save = QtWidgets.QPushButton(self.Buttons)
        self.b_save.setObjectName("b_save")
        self.verticalLayout.addWidget(self.b_save)
        self.b_load = QtWidgets.QPushButton(self.Buttons)
        self.b_load.setObjectName("b_load")
        self.verticalLayout.addWidget(self.b_load)
        self.b_undo = QtWidgets.QPushButton(self.Buttons)
        self.b_undo.setObjectName("b_undo")
        self.verticalLayout.addWidget(self.b_undo)
        self.b_redo = QtWidgets.QPushButton(self.Buttons)
        self.b_redo.setObjectName("b_redo")
        self.verticalLayout.addWidget(self.b_redo)
        self.b_delete = QtWidgets.QPushButton(self.Buttons)
        self.b_delete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.b_delete.setObjectName("b_delete")
        self.verticalLayout.addWidget(self.b_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.Buttons, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.b_finalize = QtWidgets.QPushButton(self.frame)
        self.b_finalize.setMinimumSize(QtCore.QSize(200, 0))
        self.b_finalize.setObjectName("b_finalize")
        self.gridLayout_3.addWidget(self.b_finalize, 0, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        LaneLinkEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LaneLinkEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 28))
        self.menubar.setObjectName("menubar")
        LaneLinkEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LaneLinkEdit)
        self.statusbar.setObjectName("statusbar")
        LaneLinkEdit.setStatusBar(self.statusbar)

        self.retranslateUi(LaneLinkEdit)
        QtCore.QMetaObject.connectSlotsByName(LaneLinkEdit)

    def retranslateUi(self, LaneLinkEdit):
        _translate = QtCore.QCoreApplication.translate
        LaneLinkEdit.setWindowTitle(_translate("LaneLinkEdit", "Lane Link Edit"))
        self.label.setText(_translate("LaneLinkEdit", "Actions"))
        self.b_save.setToolTip(_translate("LaneLinkEdit", "ctrl + s"))
        self.b_save.setText(_translate("LaneLinkEdit", "save"))
        self.b_load.setToolTip(_translate("LaneLinkEdit", "ctrl + l"))
        self.b_load.setText(_translate("LaneLinkEdit", "load"))
        self.b_undo.setToolTip(_translate("LaneLinkEdit", "ctrl + z"))
        self.b_undo.setText(_translate("LaneLinkEdit", "undo"))
        self.b_redo.setToolTip(_translate("LaneLinkEdit", "ctrl + shift + z"))
        self.b_redo.setText(_translate("LaneLinkEdit", "redo"))
        self.b_delete.setToolTip(_translate("LaneLinkEdit", "del"))
        self.b_delete.setText(_translate("LaneLinkEdit", "delete"))
        self.pushButton.setText(_translate("LaneLinkEdit", "Parsing"))
        self.b_finalize.setText(_translate("LaneLinkEdit", "Finalize Edit"))
        self.pushButton_2.setText(_translate("LaneLinkEdit", "Edge Editing"))
        self.pushButton_3.setText(_translate("LaneLinkEdit", "Lane Link Editing"))

