# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_apply = QtWidgets.QPushButton(self.frame)
        self.btn_apply.setObjectName("btn_close")
        self.gridLayout_3.addWidget(self.btn_apply, 0, 2, 1, 1)
        # self.btn_save = QtWidgets.QPushButton(self.frame) # TODO first provide function to load configs
        # self.btn_save.setObjectName("btn_save")
        # self.gridLayout_3.addWidget(self.btn_save, 0, 1, 1, 1)
        self.btn_restore_defaults = QtWidgets.QPushButton(self.frame)
        self.btn_restore_defaults.setObjectName("btn_restore_defaults")
        self.gridLayout_3.addWidget(self.btn_restore_defaults, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 1024))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 31, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 35, 0, 1, 1)
        self.le_tags = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_tags.setObjectName("le_tags")
        self.gridLayout_2.addWidget(self.le_tags, 5, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 33, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 20, 0, 1, 1)
        self.chk_make_contiguous = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_make_contiguous.setText("")
        self.chk_make_contiguous.setObjectName("chk_make_contiguous")
        self.gridLayout_2.addWidget(self.chk_make_contiguous, 18, 2, 1, 1)
        self.chk_utm_coordinates = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_utm_coordinates.setText("")
        self.chk_utm_coordinates.setObjectName("chk_utm_coordinates")
        self.gridLayout_2.addWidget(self.chk_utm_coordinates, 28, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1)
        self.sb_intersection_distance = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_intersection_distance.setMaximum(1000.0)
        self.sb_intersection_distance.setObjectName("sb_intersection_distance")
        self.gridLayout_2.addWidget(self.sb_intersection_distance, 35, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.le_source = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_source.setObjectName("le_source")
        self.gridLayout_2.addWidget(self.le_source, 4, 2, 1, 1)
        self.chb_aerial = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chb_aerial.setText("")
        self.chb_aerial.setObjectName("chb_aerial")
        self.gridLayout_2.addWidget(self.chb_aerial, 8, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 13, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 30, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 39, 0, 1, 1)
        self.sb_zoom_level = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.sb_zoom_level.setMinimum(1)
        self.sb_zoom_level.setMaximum(23)
        self.sb_zoom_level.setObjectName("sb_zoom_level")
        self.gridLayout_2.addWidget(self.sb_zoom_level, 10, 2, 1, 1)
        self.sb_eart_radius = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.sb_eart_radius.setMaximum(100000000)
        self.sb_eart_radius.setProperty("value", 6371000)
        self.sb_eart_radius.setObjectName("sb_eart_radius")
        self.gridLayout_2.addWidget(self.sb_eart_radius, 31, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 10, 0, 1, 1)
        self.chk_load_tunnels = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_load_tunnels.setText("")
        self.chk_load_tunnels.setObjectName("chk_load_tunnels")
        self.gridLayout_2.addWidget(self.chk_load_tunnels, 17, 2, 1, 1)
        self.chk_split_corners = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_split_corners.setText("")
        self.chk_split_corners.setObjectName("chk_split_corners")
        self.gridLayout_2.addWidget(self.chk_split_corners, 19, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 17, 0, 1, 1)
        self.le_img_save_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_img_save_path.setObjectName("le_img_save_path")
        self.gridLayout_2.addWidget(self.le_img_save_path, 9, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 16, 0, 1, 1)
        self.sb_soft_angle_treshold = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_soft_angle_treshold.setMaximum(180.0)
        self.sb_soft_angle_treshold.setObjectName("sb_soft_angle_treshold")
        self.gridLayout_2.addWidget(self.sb_soft_angle_treshold, 37, 2, 1, 1)
        self.sb_bezier_parameter = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_bezier_parameter.setMaximum(0.5)
        self.sb_bezier_parameter.setProperty("value", 0.35)
        self.sb_bezier_parameter.setObjectName("sb_bezier_parameter")
        self.gridLayout_2.addWidget(self.sb_bezier_parameter, 34, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 38, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 12, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 15, 0, 1, 1)
        self.le_benchmark_id = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_benchmark_id.setObjectName("le_benchmark_id")
        self.gridLayout_2.addWidget(self.le_benchmark_id, 1, 2, 1, 1)
        self.sb_time_step_size = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_time_step_size.setMaximum(1000.0)
        self.sb_time_step_size.setObjectName("sb_time_step_size")
        self.gridLayout_2.addWidget(self.sb_time_step_size, 6, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 0, 1, 1)
        self.le_affiliation = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_affiliation.setObjectName("le_affiliation")
        self.gridLayout_2.addWidget(self.le_affiliation, 3, 2, 1, 1)
        self.le_coordinates = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_coordinates.setObjectName("le_coordinates")
        self.gridLayout_2.addWidget(self.le_coordinates, 14, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 0, 1, 1)
        self.sb_internal_interpolation_distance = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_internal_interpolation_distance.setMinimum(0.01)
        self.sb_internal_interpolation_distance.setMaximum(1000.0)
        self.sb_internal_interpolation_distance.setObjectName("sb_internal_interpolation_distance")
        self.gridLayout_2.addWidget(self.sb_internal_interpolation_distance, 33, 2, 1, 1)
        self.btn_edit_lane_counts = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_edit_lane_counts.setObjectName("btn_edit_lane_counts")
        self.gridLayout_2.addWidget(self.btn_edit_lane_counts, 22, 2, 1, 1)
        self.btn_edit_speed_limits = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_edit_speed_limits.setObjectName("btn_edit_speed_limits")
        self.gridLayout_2.addWidget(self.btn_edit_speed_limits, 24, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 22, 0, 1, 1)
        self.chk_delete_short_edges = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_delete_short_edges.setText("")
        self.chk_delete_short_edges.setObjectName("chk_delete_short_edges")
        self.gridLayout_2.addWidget(self.chk_delete_short_edges, 32, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 25, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 19, 0, 1, 1)
        self.sb_compression_threshold = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_compression_threshold.setMaximum(1000.0)
        self.sb_compression_threshold.setObjectName("sb_compression_threshold")
        self.gridLayout_2.addWidget(self.sb_compression_threshold, 27, 2, 1, 1)
        self.btn_edit_street_types = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_edit_street_types.setObjectName("btn_edit_street_types")
        self.gridLayout_2.addWidget(self.btn_edit_street_types, 21, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 27, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 26, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 28, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 32, 0, 1, 1)
        self.le_bing_maps_key = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_bing_maps_key.setObjectName("le_bing_maps_key")
        self.gridLayout_2.addWidget(self.le_bing_maps_key, 11, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 21, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 11, 0, 1, 1)
        self.sb_interpolation_distance = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_interpolation_distance.setMinimum(0.01)
        self.sb_interpolation_distance.setMaximum(1000.0)
        self.sb_interpolation_distance.setObjectName("sb_interpolation_distance")
        self.gridLayout_2.addWidget(self.sb_interpolation_distance, 26, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 24, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 23, 0, 1, 1)
        self.chk_use_restrictions = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_use_restrictions.setText("")
        self.chk_use_restrictions.setObjectName("chk_use_restrictions")
        self.gridLayout_2.addWidget(self.chk_use_restrictions, 20, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 40, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 34, 0, 1, 1)
        self.sb_merge_distance = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_merge_distance.setMaximum(1000000.0)
        self.sb_merge_distance.setObjectName("sb_merge_distance")
        self.gridLayout_2.addWidget(self.sb_merge_distance, 41, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 18, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 37, 0, 1, 1)
        self.btn_edit_lane_widths = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_edit_lane_widths.setObjectName("btn_edit_lane_widths")
        self.gridLayout_2.addWidget(self.btn_edit_lane_widths, 23, 2, 1, 1)
        self.sb_cluster_length = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_cluster_length.setMaximum(1000000.0)
        self.sb_cluster_length.setObjectName("sb_cluster_length")
        self.gridLayout_2.addWidget(self.sb_cluster_length, 39, 2, 1, 1)
        self.sb_lane_segment_angle_treshold = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_lane_segment_angle_treshold.setMaximum(180.0)
        self.sb_lane_segment_angle_treshold.setObjectName("sb_lane_segment_angle_treshold")
        self.gridLayout_2.addWidget(self.sb_lane_segment_angle_treshold, 38, 2, 1, 1)
        self.sb_cluster_length_treshold = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_cluster_length_treshold.setMaximum(1000000.0)
        self.sb_cluster_length_treshold.setObjectName("sb_cluster_length_treshold")
        self.gridLayout_2.addWidget(self.sb_cluster_length_treshold, 40, 2, 1, 1)
        self.sb_donwload_radius = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.sb_donwload_radius.setMaximum(1000000)
        self.sb_donwload_radius.setProperty("value", 200)
        self.sb_donwload_radius.setObjectName("sb_donwload_radius")
        self.gridLayout_2.addWidget(self.sb_donwload_radius, 15, 2, 1, 1)
        self.chk_filter_points = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_filter_points.setText("")
        self.chk_filter_points.setObjectName("chk_filter_points")
        self.gridLayout_2.addWidget(self.chk_filter_points, 29, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.chk_intersection_distance_respect = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_intersection_distance_respect.setText("")
        self.chk_intersection_distance_respect.setObjectName("chk_intersection_distance_respect")
        self.gridLayout_2.addWidget(self.chk_intersection_distance_respect, 36, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 14, 0, 1, 1)
        self.le_author = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_author.setObjectName("le_author")
        self.gridLayout_2.addWidget(self.le_author, 2, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 29, 0, 1, 1)
        self.le_save_path = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.le_save_path.setObjectName("le_save_path")
        self.gridLayout_2.addWidget(self.le_save_path, 13, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 36, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 41, 0, 1, 1)

        # Sublyer extraction section
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 42, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 43, 0, 1, 1)
        self.chk_extract_sublayer = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chk_extract_sublayer.setText("")
        self.chk_extract_sublayer.setObjectName("chk_extract_sublayer")
        self.gridLayout_2.addWidget(self.chk_extract_sublayer, 43, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 44, 0, 1, 1)
        self.btn_edit_sublayer_way_types = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_edit_sublayer_way_types.setObjectName("btn_edit_sublayer_way_types")
        self.gridLayout_2.addWidget(self.btn_edit_sublayer_way_types, 44, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 45, 0, 1, 1)
        self.sb_intersection_distance_sublayer = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.sb_intersection_distance_sublayer.setMaximum(1000.0)
        self.sb_intersection_distance_sublayer.setObjectName("sb_intersection_distance_sublayer")
        self.gridLayout_2.addWidget(self.sb_intersection_distance_sublayer, 45, 2, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.btn_apply.setText(_translate("MainWindow", "Apply and close"))
        # self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_restore_defaults.setText(_translate("MainWindow", "Restore Defaults"))
        self.label_2.setText(_translate("MainWindow", "Save Path"))
        self.label_3.setText(_translate("MainWindow", "Image Save Path"))
        self.label_4.setText(_translate("MainWindow", "Zoom Level"))
        self.label_5.setText(_translate("MainWindow", "Aerial Images"))
        self.label_6.setText(_translate("MainWindow", "Show Aerial Images"))
        self.label_7.setText(_translate("MainWindow", "Map Download"))
        self.label_8.setText(_translate("MainWindow", "Donwload Radius"))
        self.label_9.setText(_translate("MainWindow", "Coordinates"))
        self.label_10.setText(_translate("MainWindow", "Benchmark"))
        self.label_12.setText(_translate("MainWindow", "Author"))
        self.label_11.setText(_translate("MainWindow", "Benchmark ID"))
        self.label_13.setText(_translate("MainWindow", "Affiliation"))
        self.label_14.setText(_translate("MainWindow", "Source"))
        self.label_15.setText(_translate("MainWindow", "Tags"))
        self.label_16.setText(_translate("MainWindow", "Timestep Size"))
        self.label_17.setText(_translate("MainWindow", "Scenario Settings"))
        self.label_18.setText(_translate("MainWindow", "Load Tunnels"))
        self.label_19.setText(_translate("MainWindow", "Make Contiguous"))
        self.label_20.setText(_translate("MainWindow", "Bing Maps Key"))
        self.label_21.setText(_translate("MainWindow", "Split at Corners"))
        self.label_22.setText(_translate("MainWindow", "Use OSM Restrictions"))
        self.label_23.setText(_translate("MainWindow", "Converted Street Types (Main)"))
        self.label_24.setText(_translate("MainWindow", "Lane Counts"))
        self.label_25.setText(_translate("MainWindow", "Lane Widths"))
        self.label_26.setText(_translate("MainWindow", "Speed Limits"))
        self.label_27.setText(_translate("MainWindow", "Export Settings"))
        self.label_28.setText(_translate("MainWindow", "Interpolation Distance"))
        self.label_29.setText(_translate("MainWindow", "Compression Threshold"))
        self.label_30.setText(_translate("MainWindow", "UTM Coordinates"))
        self.label_31.setText(_translate("MainWindow", "Internal Settings"))
        self.label_32.setText(_translate("MainWindow", "Earth Radius"))
        self.label_33.setText(_translate("MainWindow", "Internal Interpolation Distance"))
        self.label_34.setText(_translate("MainWindow", "Bezier Parameter"))
        self.label_35.setText(_translate("MainWindow", "Intersection Distance"))
        self.label_36.setText(_translate("MainWindow", "Soft Angle Threshold"))
        self.label_37.setText(_translate("MainWindow", "Lane Segment Angle Threshold"))
        self.label_38.setText(_translate("MainWindow", "Cluster Length"))
        self.label_39.setText(_translate("MainWindow", "Cluster Length Treshold"))
        self.label_40.setText(_translate("MainWindow", "Merge Distance"))
        self.label_41.setText(_translate("MainWindow", "Delete Short Edges"))
        self.label_42.setText(_translate("MainWindow", "Intersection Distance with\n"
"respect to other roads"))
        self.label_43.setText(_translate("MainWindow", "Filter Points"))
        self.label_44.setText(_translate("MainWindow", "Crossing Sublayer Settings"))
        self.label_45.setText(_translate("MainWindow", "Extract Sublayer"))
        self.label_46.setText(_translate("MainWindow", "Converted Street Types (Sub)"))
        self.label_47.setText(_translate("MainWindow", "Intersection Distance Sublayer"))
        self.btn_edit_lane_counts.setText(_translate("MainWindow", "Show"))
        self.btn_edit_speed_limits.setText(_translate("MainWindow", "Show"))
        self.btn_edit_street_types.setText(_translate("MainWindow", "Show"))
        self.btn_edit_lane_widths.setText(_translate("MainWindow", "Show"))
        self.btn_edit_sublayer_way_types.setText(_translate("MainWindow", "Show"))



