# crdesigner/common/traffic_sign_node_elevation.py
from commonroad.common.writer.file_writer_xml import (
    TrafficSignXMLNode as _TSNode,
    TrafficLightXMLNode as _TLNode,
    LaneletStopLineXMLNode as _SLNode,
    Point as _Point,
)
from lxml import etree 
def _patch_sign_writer():
    orig_create = _TSNode.create_node
    def create_with_z(ts):
        node = orig_create(ts)
        pos = getattr(ts, "position", None)
        if pos is not None and len(pos) == 3:
            x, y, z = map(float, pos)
            pos_node = node.find("position")
            if pos_node is not None:
                old_pt = pos_node.find("point")
                new_pt = _Point(x, y, z).create_node()
                if old_pt is not None:
                    pos_node.remove(old_pt)
                pos_node.append(new_pt)
        return node
    _TSNode.create_node = staticmethod(create_with_z)

def _patch_light_writer():
    orig_create = _TLNode.create_node
    def create_with_z(tl):
        node = orig_create(tl)
        pos = getattr(tl, "position", None)
        if pos is not None and len(pos) == 3:
            x, y, z = map(float, pos)
            pos_node = node.find("position")
            if pos_node is not None:
                old_pt = pos_node.find("point")
                new_pt = _Point(x, y, z).create_node()
                if old_pt is not None:
                    pos_node.remove(old_pt)
                pos_node.append(new_pt)
        return node
    _TLNode.create_node = staticmethod(create_with_z)

import xml.etree.ElementTree as ET
def _patch_stopline_writer():
    orig_create = _SLNode.create_node
    def create_with_z(sl):
        node = orig_create(sl)
        # start
        if hasattr(sl, "start") and len(sl.start) == 3:
            sx, sy, sz = map(float, sl.start)
            start_node = node.find("start")
            if start_node is not None:
                old_pt = start_node.find("point")
                new_pt = _Point(sx, sy, sz).create_node()
                if old_pt is not None:
                    start_node.remove(old_pt)
                start_node.append(new_pt)

                print("SL xml:", ET.tostring(node, encoding="unicode"))
        # end
        if hasattr(sl, "end") and len(sl.end) == 3:
            ex, ey, ez = map(float, sl.end)
            end_node = node.find("end")
            if end_node is not None:
                old_pt = end_node.find("point")
                new_pt = _Point(ex, ey, ez).create_node()
                if old_pt is not None:
                    end_node.remove(old_pt)
                end_node.append(new_pt)
                
                print("SL xml:", ET.tostring(node, encoding="unicode"))
        return node
    _SLNode.create_node = staticmethod(create_with_z)
    
def _patch_stopline_writer_z():
    orig_create = _SLNode.create_node

    def create_with_z(sl):
        """Create a stop line node with <z> in <point>."""
        node = orig_create(sl)  # use original method gernerate <stopLine> + two <point> + other nodes

        # collect the <point> children and their indices
        children = list(node)  # keep the order of children
        point_idx = [i for i, ch in enumerate(children) if ch.tag == "point"]

        def _mk_point(arr):
            if arr is None:
                return None
            x = float(arr[0]); y = float(arr[1])
            if len(arr) >= 3:
                z = float(arr[2])
                return _Point(x, y, z).create_node()
            else:
                return _Point(x, y).create_node()

        # replece the first point
        if hasattr(sl, "start"):
            new_start = _mk_point(sl.start)
            if new_start is not None:
                if len(point_idx) >= 1:
                    i0 = point_idx[0]
                    node.remove(children[i0])
                    node.insert(i0, new_start)
                else:
                    # extreme situation: no point generated by original function
                    node.insert(0, new_start)

        # replace second point and update children/point_idx
        children = list(node)
        point_idx = [i for i, ch in enumerate(children) if ch.tag == "point"]
        if hasattr(sl, "end"):
            new_end = _mk_point(sl.end)
            if new_end is not None:
                if len(point_idx) >= 2:
                    i1 = point_idx[1]
                    node.remove(children[i1])
                    node.insert(i1, new_end)
                else:
                    # if there's no second point,follow the first point or append directly
                    if len(point_idx) == 1:
                        node.insert(point_idx[0] + 1, new_end)
                    else:
                        node.append(new_end)

        return node

    _SLNode.create_node = staticmethod(create_with_z)

def patch_controls_write_3d():
    """Patch the XML writer for traffic signs, traffic lights, and stop lines to include <z> in <point>."""
    _patch_sign_writer()
    _patch_light_writer()
    _patch_stopline_writer_z()

    
    
